### ISSUE TITLE
Add a CHANGELOG

### ISSUE THREAD

**Issue by isuftin** [jfrog/jenkins-artifactory-plugin#109]
Is there somewhere I can go to find out what the latest changes were in current releases? If not, consider a CHANGELOG.md in this repository

**Comment by eyalbe4** [comment]
isuftin
See the release notes [here](https://www.jfrog.com/confluence/display/RTF/Jenkins+Artifactory+Plug-in#JenkinsArtifactoryPlug-in-ReleaseNotes).
We also updated the **General** section in the README with a link to the release notes.

**Comment by isuftin** [comment]
👍
