### ISSUE TITLE
Support for maven wrapper

### ISSUE THREAD

**Issue by manjeet88** [jfrog/jenkins-artifactory-plugin#116]
is there any support for maven wrapper for this plugin like gradle has ?

**Comment by yahavi** [comment]
@manjeet88 Currently Maven wrapper is not supported.

**Comment by alexquiti** [comment]
Is it still not supported? I mean Maven wrapper is still not supported by this plugin?

**Comment by e88z4** [comment]
+1 on this feature as well.

**Comment by SakinaMaster** [comment]
Please provide this feature.

**Comment by yahavi** [comment]
@manjeet88 @alexquiti @e88z4 @SakinaMaster 
We are working on adding this feature to the next release.
Here is the relevant PR: https://github.com/jfrog/jenkins-artifactory-plugin/pull/482

We'll keep you updated.

**Comment by yahavi** [comment]
@manjeet88 @alexquiti @e88z4 @SakinaMaster
Jenkins Artifactory plugin 3.12.1 is released. This version includes a support for Maven wrapper.

Usage is straight forward:
  * Declarative pipeline:
    ```groovy
    rtMavenRun(
            ...
            useWrapper: true
            ...
    )
    ```
  * Scripted pipeline:
    ```groovy
    def rtMaven = Artifactory.newMavenBuild()
    rtMaven.useWrapper = true
    ```

**Comment by manjeet88** [comment]
> @manjeet88 @alexquiti @e88z4 @SakinaMaster
> Jenkins Artifactory plugin 3.12.1 is released. This version includes a support for Maven wrapper.
> 
> Usage is straight forward:
> 
>     * Declarative pipeline:
>       ```groovy
>       rtMavenRun(
>               ...
>               useWrapper: true
>               ...
>       )
>       ```
> 
>     * Scripted pipeline:
>       ```groovy
>       def rtMaven = Artifactory.newMavenBuild()
>       rtMaven.useWrapper = true
>       ```
> 
> 
> We'd appreciate your feedback on that.

👍

**Comment by denhamcoote** [comment]
Please update your documentation to describe this change.

https://www.jfrog.com/confluence/display/JFROG/Declarative+Pipeline+Syntax#DeclarativePipelineSyntax-MavenBuildswithArtifactory

It's there in the example. with no explanation of what the parameter does.  I had to google search to this page to discover its usage intent.
