### ISSUE TITLE
Able to upload packages but unable to upload build info

### ISSUE THREAD

**Issue by djgoku** [jfrog/jenkins-artifactory-plugin#120]
This is the error I am getting:

I have searched but unable to find a solution.
```
java.io.IOException: Could not publish build-info: Failed to send build descriptor. 403 Response message: {
  "errors" : [ {
    "status" : 403,
    "message" : "User token:user is not permitted to deploy 'job/17-1551222119073.json' into 'artifactory-build-info:job/17-1551222119073.json'."
  } ]
}
```

**Comment by eyalbe4** [comment]
@djgoku,
Isn't this a permission issue?
Does this user have write permissions to this path in your Artifactory Build-Info repository?
Following the introduction of Build-Info repositories in Artifactory, publishing build-info is similar to the deployment of any artiifact, which requires permissions to the deployment target.

**Comment by djgoku** [comment]
@eyalbe4 Yeah you are right. I swear the Build Actions permissions were grayed out when I was setting up permissions so I only setup Repository Actions. Thanks.

**Comment by BillHoo** [comment]
Hi @eyalbe4 , I got the very same issue here, but can not find any way to set such permission in Artifactory, I'm using Artifactory OSS 6.7.0, is that too old to handle the latest jenkins plugin's data?

@djgoku Could you tell me which version of Artifactory you are using? i can not find a setting named "Build Actions" any where in my instance.

Thank you both!

**Comment by BillHoo** [comment]
Finally I find out I need to check "Any Build" in the "Add Builds" panel, and then the "Build Action" checkboxes are available ... my bad. thank you!

**Comment by spuder** [comment]
Thank you @BillHoo 
For future reference, the 'Add Builds' panel is inside the 'permissions' page. 

![Screenshot 2019-11-15 14 37 46](https://user-images.githubusercontent.com/242382/68977608-d9a27880-07b5-11ea-9734-246e65cb094c.png)
![Screenshot 2019-11-15 14 37 30](https://user-images.githubusercontent.com/242382/68977733-25552200-07b6-11ea-9d51-5761858a981c.png)
