### ISSUE TITLE
rtMavenRun cannot run with maven3 + jdk1.7

### ISSUE THREAD

**Issue by Amos-85** [jfrog/jenkins-artifactory-plugin#136]
I'm trying to compile a java application with maven 3 using jdk1.7 and the step rtMavenRun is crash cause of the jdk1.7.
it seems like the jenkins artifactory plugin using the jdk1.7 for running.

**artifactory jenkins plugin version**: 3.2.2

**steps to reproduce:**
adding this step to Jenkins pipeline file:

```
stage{
  environment{
    JAVA_HOME = 'PATH TO JDK1.7'
  }
  steps{
    rtMavenRun (
      tool: 'mvn3',
      pom: 'pom.xml',
      goals: 'clean install
      resolverId: 'artifactory',
      deployerId: 'artifactory',
      )
    }
}
```
**Exception:**
`13:25:29  [main] WARNING Sisu - Error injecting: org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder
13:25:29  java.lang.TypeNotPresentException: Type org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder not present
13:25:29      at org.eclipse.sisu.space.URLClassSpace.loadClass (URLClassSpace.java:147)
13:25:29      at org.eclipse.sisu.space.NamedClass.load (NamedClass.java:46)
13:25:29      at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
13:25:29      at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
13:25:29      at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
13:25:29      at com.google.inject.internal.SingletonScope$1.get (SingletonScope.java:168)
13:25:29      at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
13:25:29      at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
13:25:29      at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1086)
13:25:29      at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
13:25:29      at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
13:25:29      at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
13:25:29      at com.google.inject.internal.SingletonScope$1.get (SingletonScope.java:168)
13:25:29      at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
13:25:29      at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
13:25:29      at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
13:25:29      at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
13:25:29      at org.eclipse.sisu.plexus.PlexusRequirements$RequirementProvider.get (PlexusRequirements.java:250)
13:25:29      at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty (ProvidedPropertyBinding.java:48)
13:25:29      at org.eclipse.sisu.bean.BeanInjector.injectMembers (BeanInjector.java:52)
13:25:29      at com.google.inject.internal.MembersInjectorImpl.injectMembers (MembersInjectorImpl.java:160)
13:25:29      at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:124)
13:25:29      at com.google.inject.internal.ConstructorInjector.access$000 (ConstructorInjector.java:32)
13:25:29      at com.google.inject.internal.ConstructorInjector$1.call (ConstructorInjector.java:98)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
13:25:29      at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:93)
13:25:29      at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
13:25:29      at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
13:25:29      at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1086)
13:25:29      at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
13:25:29      at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
13:25:29      at org.eclipse.sisu.bean.BeanScheduler$CycleActivator.onProvision (BeanScheduler.java:230)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:120)
13:25:29      at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
13:25:29      at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
13:25:29      at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
13:25:29      at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
13:25:29      at com.google.inject.internal.SingletonScope$1.get (SingletonScope.java:168)
13:25:29      at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
13:25:29      at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
13:25:29      at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
13:25:29      at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
13:25:29      at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
13:25:29      at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
13:25:29      at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:249)
13:25:29      at org.apache.maven.cli.MavenCli.container (MavenCli.java:675)
13:25:29      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:281)
13:25:29      at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
13:25:29      at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
13:25:29      at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
13:25:29      at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
13:25:29      at java.lang.reflect.Method.invoke (Method.java:606)
13:25:29      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
13:25:29      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
13:25:29      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
13:25:29      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
13:25:29  Caused by: java.lang.UnsupportedClassVersionError: org/jfrog/build/extractor/maven/ArtifactoryProjectBuilder : Unsupported major.minor version 52.0`

**Expected behavior:**

Compiling java application with jdk 1.7 using jenkins artifactory plugin.

**Comment by barbelity** [comment]
@Amos-85,
From plugin's version 3.0.0, JDK 1.7 is not supported.
We have decided to move to 1.8 after several security issues encountered in the older version, in addition to 1.7 reaching its end-of-life stage.
You can view [our plugin's release notes](https://www.jfrog.com/confluence/display/RTF/Jenkins+Artifactory+Plug-in#JenkinsArtifactoryPlug-in-ReleaseNotes) to learn of new updates, fixes and features added in each version.

**Comment by Amos-85** [comment]
Thanks @barbelity 
Closing the issue.
