### ISSUE TITLE
NPM Publish ignores proxy settings

### ISSUE THREAD

**Issue by tomola** [jfrog/jenkins-artifactory-plugin#146]
NPM Publish (and possibly NPM Install as well) ignores _Bypass HTTP Proxy_ setting in Artifactory tool configuration and uses the global proxy to connect to Artifactory host. It also ignores no-proxy hosts specified in the global proxy settings.

```
Error occurred for request GET http://artifactory/api/system/version HTTP/1.1. Received status code 504 and message: Gateway Timeout.

Attempting retry #1
...
Attempting retry #3
...

Couldn't execute npm task. Check connection with Artifactory.

npm publish failed
```

**Comment by yahavi** [comment]
@tomola 
Thanks for reporting this issue. We fixed it!
Here is the commit that resolves the issue: https://github.com/jfrog/jenkins-artifactory-plugin/pull/217/commits/9c8182367d2a1ece5a2a7359028fc2b008723c78.
Here is a snapshot with the fix: https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.4.x-SNAPSHOT/artifactory-3.4.x-20191121.155839-23.hpi

We'll appreciate your feedback for that.
