### ISSUE TITLE
Credentials plugin not working

### ISSUE THREAD

**Issue by andreatera** [jfrog/jenkins-artifactory-plugin#149]
During the upgrade to latest plugin we recognized that the **Credential Plugin** is not working anymore:
![image](https://user-images.githubusercontent.com/15376713/59101981-04e18b80-892b-11e9-9911-7658b71bfbdb.png)

> Jenkins version: 2.164.2
> Artifactory plugin version: 3.2.4

**Comment by njtman** [comment]
I experienced this issue as well.  Downgrading the plugin fixed the problem.

**Comment by climblinne** [comment]
Same issue here. We already had updated the Artifactory plugin to 3.2.4 a few days ago. And today installed Jenkins 2.164.3-> 2.176.1

**Comment by climblinne** [comment]
@AlexeiVainshtein Could you check this one? I think you worked https://github.com/jfrog/jenkins-artifactory-plugin/commit/b69b776b41afbe09cf6c4ce797ab229c8deca039.

**Comment by climblinne** [comment]
For me downgrade from 3.2.4 to 3.2.1/3.2.2 helped. didn't check for 3.2.3

**Comment by eyalbe4** [comment]
@climblinne, @njtman and @andreatera,
Thanks for reporting this issue.
I believe @AlexeiVainshtein identified the issue and is working on a fix.
We're aiming to release it early next week.

**Comment by alexisde** [comment]
Any updates on this issue?

**Comment by climblinne** [comment]
We tested the new 3.2.5 and it worked again. So far no issues.

**Comment by fdolsky321** [comment]
@climblinne you mean 3.3.0?

**Comment by eyalbe4** [comment]
@fdolsky321 -
The fix made by @AlexeiVainshtein made it into version 3.3.0.

**Comment by climblinne** [comment]
Yes, right. The new version fixed it.
