### ISSUE TITLE
Download target keeps structure of pattern

### ISSUE THREAD

**Issue by Karanval** [jfrog/jenkins-artifactory-plugin#173]
When downloading using rtDownload, I specified
```
pattern: "[repository name]/[repository path]"
 target: "folderInWorkspace/"
```
Actual result:
- The file is downloaded with path: `folderInWorkspace/[repository name]/[repository path]`

Expected result:
- The file is download with path: `folderInWorkspace/[file(s)]`

---
Jenkins version: 2.176.2
Artifactory plugin version: 3.3.2

**Comment by eyalbe4** [comment]
@Karanval,
Please try adding **flat: "true"** to your file spec.
This should download the files without their Artifactory path.

**Comment by Karanval** [comment]
oh, now I feel dumb for not reading the full documentation. thank you for your quick reply
