### ISSUE TITLE
Create artifactory triggers using declarative pipeline

### ISSUE THREAD

**Issue by souris4science** [jfrog/jenkins-artifactory-plugin#175]
Being able to specify the job triggers in the Jenkinsfile script using declarative pipeline is a useful feature that allows to have configuration as code and therefore be stored in a repository.
At the moment there is this `triggers` directive in declarative pipeline that supports `cron`, `pollSCM` and `upstream` triggers. In that sense it would be useful to support also the artifactory trigger, so one can set up such trigger using for example the following code:

```
pipeline {
    agent any
    triggers {
        artifactory(serverId: 'AF_SERVER', schedule: 'H */4 * * 1-5', paths: 'generic-libs-local/builds/starship')
    }
    ...
}
```

**Comment by GordonJess** [comment]
It would be useful to trigger on updates to any of the dependencies.  Can we perhaps add an option that adds these paths?  Seems a common use case.

**Comment by angegar** [comment]
Is it linked with :

![image](https://user-images.githubusercontent.com/5628764/77754894-81656800-702c-11ea-8ea7-57e9fbf1fc4f.png)

I get this screenshot from : https://jenkins.io/doc/pipeline/steps/workflow-multibranch/#-properties-%20set%20job%20properties

**Comment by yahavi** [comment]
@souris4science @angegar,
Thanks for asking this feature!
Jenkins Artifactory plugin 3.8.0 is released. Per your request, we added this new feature.
For the declarative pipeline, we added a new step `rtBuildTrigger`:
```groovy
rtBuildTrigger(
    serverId: "AF_SERVER",
    spec: "H */4 * * 1-5",
    paths: "generic-libs-local/builds/starship"
)
```
The reason for adding a new step, unlike using the `triggers` DSL is that we wanted to support also servers defined in the pipeline, using the `rtServer` step. We also found this approach more robust and extendable.
To be more clear - this step supports either selecting a server from the global configuration, as above, and also using servers defined in pipeline scripts - see examples for [declarative](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/build-trigger-example/Jenkinsfile) pipeline and [scripted](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/build-trigger-example/Jenkinsfile) pipeline. 

The official documentation will be updated soon.
We'll appreciate your feedback for that!

**Comment by yahavi** [comment]
**Documentation:**
1. Scripted pipeline: https://www.jfrog.com/confluence/display/JFROG/scripted+Pipeline+Syntax#ScriptedPipelineSyntax-DefiningBuildTriggers
2. Declarative pipeline: https://www.jfrog.com/confluence/display/JFROG/Declarative+Pipeline+Syntax#DeclarativePipelineSyntax-DefiningBuildTriggers

Please let us know if that helps.

**Comment by tibco-postman** [comment]
Is this a step that should be placed in a stage block, or somewhere else?

**Comment by yahavi** [comment]
@tibco-postman Yes, for example:
```groovy
stage ('Add build trigger') {
    steps {
        rtBuildTrigger(
            serverId: "ARTIFACTORY_SERVER",
            spec: "*/10 * * * *",
            paths: "generic-libs-local/builds/starship"
       )
    }
}
```
See full declarative example [here](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/build-trigger-example/Jenkinsfile) and scripted example [here](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/build-trigger-example/Jenkinsfile).

**Comment by pradeepnnv** [comment]
@yahavi , does the spec field in rtBuildTrigger support Jenkins cron sytax?

https://www.jenkins.io/doc/book/pipeline/syntax/#cron-syntax

**Comment by pradeepnnv** [comment]
@yahavi , Can the path be a regex pattern? 
If I want to trigger the build when a specific docker tag is pushed to repo instead of all tags, having a regex pattern will be helpful.

**Comment by eyalbe4** [comment]
@pradeepnnv - yes, the same cron syntax used for the SCM Trigger (and probably other triggers) is used for the Artifactory Trigger. 

@pradeepnnv - patterns are currently not supported. You need to specify a path in Artifactory. 
This however can be a nice feature request. Feel free to open one, with a description of the use case.

**Comment by pradeepnnv** [comment]
Thanks @eyalbe4  for responding. I will create a new feature request for regex.

**Comment by eyalbe4** [comment]
I guess this issue can be closed. Closing.

**Comment by saranbabu33** [comment]
@eyalbe4 @pradeepnnv I have two CI jobs, 1st Job pushes the binary to Jfrog artifactory and then I want to trigger the 2nd Job automatically when a new push happened in the artifactory server. Is the above pipeline script works for it?
