### ISSUE TITLE
NotSerializableException for CollectIssuesExecutor when running rtCollectIssues

### ISSUE THREAD

**Issue by NilsVensler** [jfrog/jenkins-artifactory-plugin#195]
When running the sample code to collect Issues in declarative pipelines everything works fine as long as the job is executed on master (docker/linux). Forcing the same pipeline to run on a different node (Windows or macOS) job fails with `java.io.NotSerializableException: org.jfrog.hudson.pipeline.common.executors.CollectIssuesExecutor
[...]`.

Download, upload and publish work on all machines.

**Comment by RobiNino** [comment]
Hi @NilsVensler,
Thanks for reporting this issue!

We added a snapshot with a solution to this issue to the JIRA that tracks it:
[HAP-1236](https://www.jfrog.com/jira/browse/HAP-1236?focusedCommentId=71872&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-71872)

We'd appreciate your feedback for it.

**Comment by RobiNino** [comment]
Artifactory-Plugin version 3.4.1 was released and includes a fix to this issue.
We'd appreciate your feedback for it.

**Comment by NilsVensler** [comment]
I left a comment at [HAP-1236](https://www.jfrog.com/jira/browse/HAP-1236).
