### ISSUE TITLE
Is it possible to collectIssues if we use Subversion ?

### ISSUE THREAD

**Issue by c-koell** [jfrog/jenkins-artifactory-plugin#207]
Hi !

We are using Subversion as SCM but as i can see rtCollectIssues always tries to read git logs .. right ?

Is it possible to collect issues also with subversion.
Ist it possible to read the scm log ?

thanks
claus

**Comment by peteneal100** [comment]
I think it would be good to feed it the "Changes" that Jenkins creates.
That way it could work on any Jenkins SCM plugin that can generate  "Changes".

We using the google repo SCM plugin and it would be great to have the change list from Jenkins in Artifactory.

**Comment by eyalbe4** [comment]
@c-koell - Currently only git is supported, but adding other SCMs is definitely something we'd like to see added.
@peteneal100 - Thanks for suggesting this. I guess the existing issues tracking configuration can be used to also collect the list of issues generated by other plugins.

**Comment by peteneal100** [comment]
yes, I'm looking at the doing something with "currentBuild.changeSets",  just thought it would be cool to somehow pass that into rtCollectIssues and leverage all its goodness.
