### ISSUE TITLE
Declarative rtServer without a credentialsId results in a NPE

### ISSUE THREAD

**Issue by reenberg** [jfrog/jenkins-artifactory-plugin#225]
The following example declarative pipeline, which doesn't specify any `credentialsId`, will throw a NullPointerException.

```groovy
pipeline {
    agent any
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/jfrog/project-examples.git"
            }
        }

        stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: "ARTIFACTORY_SERVER",
                    url: "http://artifactory:8081/artifactory",
                    //credentialsId: CREDENTIALS
                )
            }
        }

        stage ('Exec Maven') {
            steps {
                rtMavenRun (
                    tool: 'mvn3', // Tool name from Jenkins configuration
                    pom: 'maven-example/pom.xml',
                    goals: 'clean install',
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "ARTIFACTORY_SERVER"
                )
            }
        }
    }
}
```

Error from the console

```
java.lang.NullPointerException
	at org.jfrog.hudson.pipeline.declarative.utils.DeclarativePipelineUtils.getArtifactoryServer(DeclarativePipelineUtils.java:83)
	at org.jfrog.hudson.pipeline.declarative.steps.PublishBuildInfoStep$Execution.run(PublishBuildInfoStep.java:63)
	at org.jfrog.hudson.pipeline.declarative.steps.PublishBuildInfoStep$Execution.run(PublishBuildInfoStep.java:42)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousStepExecution.start(AbstractSynchronousStepExecution.java:42)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
...
```

This happens due to the fact that [DeclarativePipelineUtils.java#L83](https://github.com/yahavi/jenkins-artifactory-plugin/blob/879ba6cb7b5ba14c7ff3ffb4184e4fa249744eb5/src/main/java/org/jfrog/hudson/pipeline/declarative/utils/DeclarativePipelineUtils.java#L83) does a unconditional lookup of the "credentialsId" in the `JsonNode` which in this case returns `null`, for which the `asText()` is called.

This NPE is thrown for any declarative step that tries to use the server reference (e.g., a `rtMavenDeployer` or `rtMavenResolver`).

According to the [Declarative Pipeline documentation](https://www.jfrog.com/confluence/display/RTF/Declarative+Pipeline+Syntax), it seems optional whether I need to specify a "credentialsID".
```groovy
rtServer (
    id: 'Artifactory-1',
    url: 'http://my-artifactory-domain/artifactory',
    // If you're using username and password:
    username: 'user',
    password: 'password'
    // If you're using Credentials ID:
    credentialsId: 'ccrreeddeennttiiaall'
    // If Jenkins is configured to use an http proxy, you can bypass the proxy when using this Artifactory server:
    bypassProxy: true
    // Configure the connection timeout (in seconds).
    // The default value (if not configured) is 300 seconds:
    timeout = 300
)
```

I guess the above lookup in the datafile should handle the case of "credentialsID" not being there, for the anonymous use cases.

**Comment by yahavi** [comment]
Thanks for reporting this issue, @reenberg.
I created a pull request that resolves it: https://github.com/jfrog/jenkins-artifactory-plugin/pull/227
Here is the [Jira](https://www.jfrog.com/jira/browse/HAP-1264) issue.
We'll keep you updated.

**Comment by yahavi** [comment]
And here is a snapshot with the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.4.x-SNAPSHOT/artifactory-3.4.x-20191208.130532-27.hpi
We'll appreciate your feedback for that!

**Comment by reenberg** [comment]
Nice.  

It would be nice if the docs was updated with a reference to what takes precedence if all three are specified, as this is now possible, as opposed to the old code. 
With the old if statement that got removed at line [#84](https://github.com/jfrog/jenkins-artifactory-plugin/pull/227/files#diff-e33f85c57336992019f1c657b2445841L84), the `ArtifactoryServer` object was only set with one of the two (credentials or user/pass).  

Personally I would have preferred an error if both a credentialsId and user/pass was supplied.  Especially since, there might be some people who have defined `rtServer` in their declarative pipeline, which for historical reasons have set `credentialsID: ""` or something, to work around the NPE when using user/password.
