### ISSUE TITLE
Docker push step stuck indefinitely

### ISSUE THREAD

**Issue by schuch** [jfrog/jenkins-artifactory-plugin#267]
When upgrading from 3.2.4 to 3.3.0 (or above) the docker push step hangs _indefinitely_.

```
[Pipeline] dockerPushStep
Pushing image: "docker-repo.ourartifactory.domain/playground/simple-jenkins-docker-pipeline:2
```

Example Jenkins File
```
def artifactory = Artifactory.server('artifactory')

pipeline {
    agent any
    stages {
        stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: "artifactory"
                )
            }
        }

        stage('Build') {
            steps {
                sh "docker build . -t docker-repo.ourartifactory.domain/playground/simple-jenkins-docker-pipeline:$currentBuild.number"
            }
        }

        stage ('Push image to Artifactory') {
            steps {
                script {
                    def rtDocker = Artifactory.docker server: artifactory
                    def dockerBuildInfo1 = rtDocker.push("docker-repo.ourartifactory.domain/playground/simple-jenkins-docker-pipeline:$currentBuild.number", "docker-repo")
                }
            }
        }
    }
}
```
The artifactory server `artifactory` is defined in the global jenkins configuration.

Unfortunately, we do not find any information about the cause of the error in the logs or in the ThreadDump.

Do you have any idea what could cause such an issue?

We use Jenkins `2.229` and Artifactory `6.11.7`

according to our analysis, the error should lie in one of these changes:
https://github.com/jenkinsci/artifactory-plugin/compare/artifactory-3.2.4...jfrog:artifactory-3.3.0

**Comment by eyalbe4** [comment]
@schuch,
Could it be that the docker daemon is accessible in a different port than the default? If so, the host argument with the daemon host and port may need to be added, as described in the Artifactory Plugin documentation.

**Comment by schuch** [comment]
Thanks for the hint @eyalbe4. We will check that and report.

**Comment by schuch** [comment]
Jenkins is running in a docker-compose setup. The docker deamon is accessible on `tcp://dockerhttp:2375`.

The host `dockerhttp` is a small sidecar container, that exposes the docker deamon of the docker host to the composed network.

In the jenkins container, the environment variable `DOCKER_HOST=tcp://dockerhttp:2375` is exported.

We will test, if it helps to specify the `host` to the `rtDocker` explicitely.

**Comment by schuch** [comment]
We changed

```
def rtDocker = Artifactory.docker server: artifactory"
```

to

```
def rtDocker = Artifactory.docker server: artifactory, host: "tcp://dockerhttp:2375"
```
but the push is still hanging:

```
[Pipeline] dockerPushStep
Pushing image: docker-repo.ourartifactory.domain/playground/simple-jenkins-docker-pipeline:10 using docker daemon host: tcp://dockerhttp:2375
(... hangs here...)
```

**Comment by schuch** [comment]
This issues seems to be fixed. After Upgrade to 3.10.3 we did no longer encounter hanging docker push steps.

Probably this was adressed with https://www.jfrog.com/jira/browse/HAP-1375, https://github.com/jfrog/jenkins-artifactory-plugin/issues/268
