### ISSUE TITLE
Conan Client has incorrect file separators when using CONAN_USER_HOME in multi-node setup

### ISSUE THREAD

**Issue by jmrandol** [jfrog/jenkins-artifactory-plugin#281]
I have a Jenkins master that runs on Windows, and a slave that runs Ubuntu.  When I run a parallel build on both Windows and Ubuntu, I have issues with the conan client changing the file separators in CONAN_USER_HOME on the Ubuntu node.

Brief code snippet:

```
echo "CONAN_USER_HOME is ${env.CONAN_USER_HOME}"
def conanClient = Artifactory.newConanClient()

```

Abbreviated Results:

```
CONAN_USER_HOME is /var/jenkins/workspace/conan

sh -c 'conan config set log.trace_file=\"\\var\\jenkins\\workspace\\conan/conan_log.log\" '

Exception: Invalid CONAN_USER_HOME value '\var\jenkins\workspace\conan', please specify an absolute or path starting with ~/ (relative to user home)

Conan build failed
```

I poked around the code a little and saw [here](https://github.com/jfrog/jenkins-artifactory-plugin/blob/676c62b3031dfdac6b81275eace6eed9bf9a458c/src/main/java/org/jfrog/hudson/pipeline/scripted/steps/conan/InitConanClientStep.java#L77):

                conanHomeDirectory = env.containsKey(Utils.CONAN_USER_HOME) ? new FilePath(new File(env.get(Utils.CONAN_USER_HOME))) : createConanTempHome();

That by using `java.io.File` it would use the master and so the path would, in my case, turn into a Windows style path.

**Versions**
- Jenkins Artifactory plugin version: 3.6.1
- Jenkins operating system: Windows Server 2016

**Comment by jmrandol** [comment]
BTW, setting userHome in `Artifactory.newConanClient(userHome: env.CONAN_USER_HOME)` solves my immediate problem.

**Comment by liron-shalom** [comment]
Hi @jmrandol,
Thanks for reporting this issue, a [fix](https://github.com/jfrog/jenkins-artifactory-plugin/pull/296) was merged into the master branch, and will be included in the next official release.
Meanwhile, we've created a snapshot, which can be downloaded [here](https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.7.x-SNAPSHOT/artifactory-3.7.x-20200709.055906-7.hpi).
We will appreciate your feedback!
