### ISSUE TITLE
uploading files while maintaining their folder structure - partially.

### ISSUE THREAD

**Issue by moshavnik** [jfrog/jenkins-artifactory-plugin#288]
Hi,

(Jfrog artifactory 6.11.1, Artifactory plugin 3.6.2)

We are trying to upload files to a generic repo, filespec is:

pattern: "${WORKSPACE}/"
target: "somereponame/${BUILD_NUMBER}"
flat: false

lets say the workspace is d:\jenkins\workspace (yes, we are using windows).
inside that folder we have a file called somefile.txt and a folder called internalfolder.
inside internal folder we have another file, called internalfile.txt

I would expect this scenario to upload "somefile.txt" to the repo, under the build number, and the internalfile.txt to a folder from that build number.

instead, the entire directory structure (including d:\jenkins\workspace) is uploaded, and the result is an entry in the repo called:

"<the actual build number>/d:/jenkins/workspace/internalfolder"

and the internalfile.txt is the only file I see.

what am I doing wrong?

I think it has something to do with [HAP-1022](https://www.jfrog.com/jira/browse/HAP-1022)

**Comment by RobiNino** [comment]
Hi @moshavnik ,
The JIRA you referred to was opened after a bug fix. The behaviour described there is the expected behaviour. As suggested in the comments, you can achieve your desired functionality by using [Place Holders](https://www.jfrog.com/confluence/display/JFROG/Using+File+Specs#UsingFileSpecs-UsingPlaceholders):
```
{
  "files": [
    {
      "pattern": "${WORKSPACE}/(*)",
      "target": "somereponame/${BUILD_NUMBER}/{1}",
      "flat": "true",
      "recursive": "true"
    }
  ]
}
```

Let us know if this does the trick for you.

**Comment by RobiNino** [comment]
Hi @moshavnik ,
I'm closing this issue now, feel free to reach out if you need any further assistance with the matter.
Thanks
