### ISSUE TITLE
Version 3.7.1 unavailable despite being included in the manifest

### ISSUE THREAD

**Issue by fasatrix** [jfrog/jenkins-artifactory-plugin#305]
**Describe the bug**
Version 3.7.1 isn't available despite  being included in the manifest

**To Reproduce**
Download : https://updates.jenkins.io/2.235/latest/artifactory-plugin.hpi

**Expected behavior**
Manifest should be in line with code repo

**Screenshots**
Available:
![image](https://user-images.githubusercontent.com/16127426/86855822-3f5dbf00-c10f-11ea-80cc-0c528ea1a2b2.png)
Failed downloading:
![image](https://user-images.githubusercontent.com/16127426/86855789-3371fd00-c10f-11ea-9e31-cc7d8e7c2207.png)
![image](https://user-images.githubusercontent.com/16127426/86856664-e4c56280-c110-11ea-823a-dbf18e66d026.png)

**Versions**
- Jenkins Artifactory plugin version: 3.7.1
- Jenkins operating system: Linux/Wondows
- Artifactory Version:

**Additional context**
We have an overnight automated deployment which upgrades Jenkins to the latest plugins available , including Artifactory. It would be greatly appreciated if you could fix the process at your end as this has happened multiple times in the past and still happening very often.

Thx

**Comment by eyalbe4** [comment]
Thanks for reporting this @fasatrix.
We're not yet sure what caused this issue. We're currently trying to redeploy the version.

**Comment by eyalbe4** [comment]
We sent an email to jenkins-infra@googlegroups.com asking for their help in resolving this issue.

**Comment by eyalbe4** [comment]
@fasatrix,
The issue seems to be resolved now. We didn't actually take any action.
Please let us know that all is good on your end and feel free to close this issue if it is.
Thanks

**Comment by fasatrix** [comment]
@eyalbe4 thanks for the prompt response.. it works now.
