### ISSUE TITLE
Facing issue when trying to uploading artifacts into jfrog using maven 

### ISSUE THREAD

**Issue by satheesh420** [jfrog/jenkins-artifactory-plugin#324]
jenkins file:
stage('Artifactory upload'){
			steps{
				script{
					def server = Artifactory.server('Artifactory-server')
					def rtMaven = Artifactory.newMavenBuild()
					rtMaven.resolver server: server, releaseRepo: 'lla-esb-release', snapshotRepo: 'lla-esb-snapshot'
					rtMaven.deployer server: server, releaseRepo: 'lla-esb-release', snapshotRepo: 'lla-esb-snapshot'
					def buildInfo = rtMaven.run pom: 'pom.xml', goals: 'clean install'
					server.publishBuildInfo buildInfo
		   	 		}	
		   		}
	    	}

and error i am getting when i run job:

[main] WARNING org.codehaus.plexus.PlexusContainer - The POM for org.mule.tools.maven:mule-maven-plugin:jar:3.3.5 is missing, no dependency information available
[main] ERROR org.apache.maven.DefaultMaven - [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.mule.tools.maven:mule-maven-plugin:3.3.5 or one of its dependencies could not be resolved: Failure to find org.mule.tools.maven:mule-maven-plugin:jar:3.3.5 in http://AA.AA.SS.XX:8081/artifactory/lla-esb-release was cached in the local repository, resolution will not be reattempted until the update interval of artifactory-release has elapsed or updates are forced @ 
[ERROR] Unknown packaging: mule-application @ line 8, column 13
 @ 
[main] ERROR org.apache.maven.cli.MavenCli - The build could not read 1 project -> [Help 1]
[main] ERROR org.apache.maven.cli.MavenCli -   
[main] ERROR org.apache.maven.cli.MavenCli -   The project com.mycompany:sample:1.1.5-SNAPSHOT (/var/lib/jenkins/workspace/Munittest-sampleproject/pom.xml) has 2 errors
[main] ERROR org.apache.maven.cli.MavenCli -     Unresolveable build extension: Plugin org.mule.tools.maven:mule-maven-plugin:3.3.5 or one of its dependencies could not be resolved: Failure to find org.mule.tools.maven:mule-maven-plugin:jar:3.3.5 in http://AA.AA.SS.XX:8081/artifactory/lla-esb-release was cached in the local repository, resolution will not be reattempted until the update interval of artifactory-release has elapsed or updates are forced -> [Help 2]
[main] ERROR org.apache.maven.cli.MavenCli -     Unknown packaging: mule-application @ line 8, column 13
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[main] ERROR org.apache.maven.cli.MavenCli - [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by eyalbe4** [comment]
@satheesh420,
Was the issue resolved?
