### ISSUE TITLE
"used by" and dependency don't get update when using jenkins rtdownload and publish build info.

### ISSUE THREAD

**Issue by levdor** [jfrog/jenkins-artifactory-plugin#336]
"used by" and dependency don't get update when using jenkins rtdownload and publish build info.

I created jenkinsfile with 4 stages:

rtdownload of files from artifactory to specific local locations
maven install which creates an rpm.
rtupload which uploads the new rpm to the artifactory.
rtPublishBuildInfo - as described above.
The rpm uploaded can be seen under "artifacts" of the build in the artifactory builds page. BUT - The files that were downloaded in step 1 are not being added as dependencies of the build (and the build not added to the "used by" list).

**Comment by eyalbe4** [comment]
@levdor,
Thanks for reporting this issue!
Can you please share you Jenkinsfile with us?

**Comment by levdor** [comment]
`pipeline {
    agent {
        label '***'
    }
    environment {
        MAVEN_HOME = "/usr/share/apache-maven-3.6.3"
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:'10'))
        timeout(time: 1, unit:'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage ('Prep') {
            steps{
                script{
                    shell.runCommand('git clean -dfx')
                }
            }
        }
        stage('Download from jfrog') {
            steps{
                script {
                    error_level=0
                    def records = readYaml file: 'jfrog_download_recipe.yaml'
                    for (int i = 0; i < records.items.size(); i++){
                        for (int j = 0; j < records.items[i]["what_to_download"].size(); j++){
                            try{
                                if (records.items[i]["download_source"] == "jfrog"){
                                    rtBuildInfo (
                                        captureEnv: true,
                                    )
                                    rtDownload (
                                            serverId: 'Artifactory',
                                            spec: """{
                                                "files": [
                                                    {
                                                    "pattern": "${records.items[i]['what_to_download'][j]}",
                                                    "sortBy": ["name"],
                                                    "sortOrder": "desc",
                                                    "limit": 1,
                                                    "target": "${records.items[i]['where_to_download']}"
                                                    }
                                                ]
                                            }""",
                                    )
                                }
                            }
                            catch (exception){
                                echo "could not download: "+"\""+records.items[i]["what_to_download"][j]+"\""+" to: "+"\""+env.WORKSPACE+"/"+records.items[i]["where_to_download"]+"\""
                                error_level+=1
                            }
                        }
                    }
                    if (error_level!=0){
                        error("this stage has failed")
                        currentBuild.result = "FAILURE"
                    }
                }
            }
        }
        stage('maven install') {
            steps{
                script {
                    // sh "mvn clean install"
                    rtMavenRun (
                        pom: './pom.xml',
                        goals: 'clean install'
                    )
                }
            }
        }
        stage('Upload to jfrog artifactory') {
            steps{
                script {
                    error_level=0
                    def records = readYaml file: 'jfrog_upload_recipe.yaml'
                    for (int i = 0; i < records.items.size(); i++){
                        for (int j = 0; j < records.items[i]["what_to_upload"].size(); j++){
                            try{
                                if (records.items[i]["upload_source"] == "jfrog"){
                                    rtBuildInfo (
                                        captureEnv: true,
                                    )
                                    rtUpload (
                                        serverId: 'Artifactory',
                                        spec: """{
                                            "files": [
                                                {
                                                "pattern": "${records.items[i]['what_to_upload'][j]}",
                                                "props": "build.url=${BUILD_URL}",
                                                "target": "${records.items[i]['where_to_upload']}"
                                                }
                                            ]
                                        }""",
                                    )
                                }
                            }
                            catch (exception){
                                echo "could not upload: "+"\""+env.WORKSPACE+"/"+records.items[i]['what_to_upload'][j]+"\""+" into: "+"\""+records.items[i]['where_to_upload']+"\""
                                error_level+=1
                            }
                        }
                    }
                    if (error_level!=0){
                        error("this stage has failed")
                        currentBuild.result = "FAILURE"
                    }
                }
            }
        }
        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "Artifactory"
                )
            }
        }
    }
    post {
        success {
            cleanWs()
        }
    }
}

`

The path is taken for a yaml file.. working great except the artifatory not updating that rtdownloaded file to be a dependency and not inserting the build into the "used by" of the downloaded file.

**Comment by levdor** [comment]
```
pipeline {
    agent {
        label '***'
    }
    environment {
        MAVEN_HOME = "/usr/share/apache-maven-3.6.3"
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:'10'))
        timeout(time: 1, unit:'HOURS')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage ('Prep') {
            steps{
                script{
                    shell.runCommand('git clean -dfx')
                }
            }
        }
        stage('Download from jfrog') {
            steps{
                script {
                    error_level=0
                    def records = readYaml file: 'jfrog_download_recipe.yaml'
                    for (int i = 0; i < records.items.size(); i++){
                        for (int j = 0; j < records.items[i]["what_to_download"].size(); j++){
                            try{
                                if (records.items[i]["download_source"] == "jfrog"){
                                    rtBuildInfo (
                                        captureEnv: true,
                                    )
                                    rtDownload (
                                            serverId: 'Artifactory',
                                            spec: """{
                                                "files": [
                                                    {
                                                    "pattern": "${records.items[i]['what_to_download'][j]}",
                                                    "sortBy": ["name"],
                                                    "sortOrder": "desc",
                                                    "limit": 1,
                                                    "target": "${records.items[i]['where_to_download']}"
                                                    }
                                                ]
                                            }""",
                                    )
                                }
                            }
                            catch (exception){
                                echo "could not download: "+"\""+records.items[i]["what_to_download"][j]+"\""+" to: "+"\""+env.WORKSPACE+"/"+records.items[i]["where_to_download"]+"\""
                                error_level+=1
                            }
                        }
                    }
                    if (error_level!=0){
                        error("this stage has failed")
                        currentBuild.result = "FAILURE"
                    }
                }
            }
        }
        stage('maven install') {
            steps{
                script {
                    // sh "mvn clean install"
                    rtMavenRun (
                        pom: './pom.xml',
                        goals: 'clean install'
                    )
                }
            }
        }
        stage('Upload to jfrog artifactory') {
            steps{
                script {
                    error_level=0
                    def records = readYaml file: 'jfrog_upload_recipe.yaml'
                    for (int i = 0; i < records.items.size(); i++){
                        for (int j = 0; j < records.items[i]["what_to_upload"].size(); j++){
                            try{
                                if (records.items[i]["upload_source"] == "jfrog"){
                                    rtBuildInfo (
                                        captureEnv: true,
                                    )
                                    rtUpload (
                                        serverId: 'Artifactory',
                                        spec: """{
                                            "files": [
                                                {
                                                "pattern": "${records.items[i]['what_to_upload'][j]}",
                                                "props": "build.url=${BUILD_URL}",
                                                "target": "${records.items[i]['where_to_upload']}"
                                                }
                                            ]
                                        }""",
                                    )
                                }
                            }
                            catch (exception){
                                echo "could not upload: "+"\""+env.WORKSPACE+"/"+records.items[i]['what_to_upload'][j]+"\""+" into: "+"\""+records.items[i]['where_to_upload']+"\""
                                error_level+=1
                            }
                        }
                    }
                    if (error_level!=0){
                        error("this stage has failed")
                        currentBuild.result = "FAILURE"
                    }
                }
            }
        }
        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "Artifactory"
                )
            }
        }
    }
    post {
        success {
            cleanWs()
        }
    }
}


```

**Comment by levdor** [comment]
The path is taken for a yaml file.. working great except the artifatory not updating that rtdownloaded file to be a dependency and not inserting the build into the "used by" of the downloaded file.

**Comment by eyalbe4** [comment]
@DorL1,
I didn't yet get a chance to look into this...
Were you able to resolve the issue? Just saw you closed the issue.
