### ISSUE TITLE
Build Info links are broken for Artifactory 7

### ISSUE THREAD

**Issue by catholic-indulgence-vaper** [jfrog/jenkins-artifactory-plugin#337]
**Describe the bug**
Jenkins plugin generates link with path /webapp, which doesn't exit in Artifactory since version 7.

**To Reproduce**
```
def art = Artifactory.newServer(url: 'https://artifactory.localdomain/artifactory', credentialsId: 'credentials id here');
def art_docker = Artifactory.docker (server: art);
def build_info = art_docker.push ('image:tag', 'docker.artifactory.localdomain');
art.publishBuildInfo(build_info);

```

**Expected behavior**
Build link in Jenkins leads to build info in Artifactory. Here's an example link:
https://artifactory.localdomain/artifactory/webapp/builds/path-1%20%3A%3A%20path-2%20%3A%3A%20img-name/123

**Versions**
- Jenkins Artifactory plugin version: 3.7.3
- Jenkins operating system: Docker image jenkins:2.256-slim
- Artifactory Version: 7.7.3

**Comment by eyalbe4** [comment]
@catholic-indulgence-vaper - thank you for reporting this issue!
I believe version 7.5.0 of Artifactory resolves this issue. See [RTFACT-21885](https://www.jfrog.com/jira/browse/RTFACT-21885).
Please let us know once the issue is resolved for you.

**Comment by tapioreijonen** [comment]
We also have Artifactory Version: 7.7.3 and see this same problem.

**Comment by catholic-indulgence-vaper** [comment]
@eyalbe4 we are running 7.7.3, which is higher version than 7.5.0.

**Comment by eyalbe4** [comment]
[RTFACT-21885](https://www.jfrog.com/jira/browse/RTFACT-21885) has been updated with a new version ETA.
See the comment added by Ben Ifrach.

**Comment by catholic-indulgence-vaper** [comment]
Upgrading to artifactory-pro:7.10.2 completely solved this issue.
