### ISSUE TITLE
Xray Scan Report link on the left panel is broken when there are special characters in the build name

### ISSUE THREAD

**Issue by hanankem** [jfrog/jenkins-artifactory-plugin#340]
**Describe the bug**
The link that is pointing to Xray scan results on the left panel is dead. The link on the main window works as expected.

**To Reproduce**
Use the pipeline script to build "test project", and add an Xray scan stage.
This will result in a broken link to Xray scan report on the left panel, and a working link on the main page.

**Expected behavior**
Both links should be working

**Screenshots**
![xray-link](https://user-images.githubusercontent.com/67636797/93317838-98845600-f816-11ea-890e-34364c20226b.png)

**Versions**
- Jenkins Artifactory plugin version: 3.8.1
- Jenkins operating system: 2.235.5
- Artifactory Version: Cloud

**Comment by yahavi** [comment]
Thanks for reporting this issue, @hanankem.
We merged the fix into the master branch. The fix will be included in the next release.
Here is a snapshot:
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.8.x-SNAPSHOT/artifactory-3.8.x-20200922.092409-7.hpi

We'd appreciate your feedback for that.

**Comment by yahavi** [comment]
@hanankem,
Jenkins Artifactory plugin 3.9.0 is released. This version includes a fix for this issue. Feel free to upgrade!
We'd appreciate your feedback for that.
