### ISSUE TITLE
Compatibility with layout changing to divs

### ISSUE THREAD

**Issue by timja** [jfrog/jenkins-artifactory-plugin#350]
**Describe the bug**
Freestyle build layout completely breaks when installing the artifactory plugin and using the div layout

the core PR shipped in 2.264. 
It will be approximately 3 months before this makes it to an LTS version, but weekly users will be affected until this plugin is made compatible

**To Reproduce**
run with Jenkins 2.264 or greater

**Expected behavior**
Freestyle page layout is not broken

**Screenshots**

<details>
<summary>Screenshot (huge)</summary>

![image](https://user-images.githubusercontent.com/21194782/96086256-f5c50300-0eb9-11eb-82e7-e09df003f3a5.png)

</details>

**Additional context**
An initial attempt was here:
https://github.com/jfrog/jenkins-artifactory-plugin/pull/279

instructions on mailing list: https://groups.google.com/d/msg/jenkinsci-dev/MpJMqa1Yc9A/Vex1yix8AAAJ
core PR: https://github.com/jenkinsci/jenkins/pull/3895

migration how-to guides: https://www.jenkins.io/doc/developer/views/table-to-div-migration/

**Comment by SubshellDaniel** [comment]
Jenkins 2.264 contains the layout changes. After updating our Jenkins the configuration page layout is broken as stated above. We are using version 3.9.0 of the Artifactory Plugin. Any plans on updating the layout?

**Comment by vwbusguy** [comment]
It seems to be broken in 2.265 as well, which is to be expected.

**Comment by rdburns** [comment]
We have this problem, and we're not sure we can safely downgrade to 2.263.

**Comment by saibots** [comment]
We have the same problem

**Comment by thomas-hammond** [comment]
We have the same problem with 2.266. Can't save changes to freestyle job configs, Save button doesn't work, Apply button shows an error.

**Comment by NickCv5** [comment]
We have the same problem. Using 3.9.0 of the Artifactory plugin. Also happened with the previous version of the Artifactory plugin. Jenkins version 2.266.

**Comment by Smasherr** [comment]
Our Jenkins instance is also affected by this issue

**Comment by RobiNino** [comment]
Thank you all for reporting this issue.
We just released version 3.9.1 of the plugin which includes a fix.
We'd appreciate your feedback for it.
