### ISSUE TITLE
Missing traces from console output

### ISSUE THREAD

**Issue by dlinares-linux** [jfrog/jenkins-artifactory-plugin#363]
**Describe the bug**
During an upload, the traces appearing in the Jenkins console output showing which artifacts have been uploaded seem to be inconsistent. Sometimes the lines "[consumer_0] Deploying artifact: http://...." are printed, sometimes they are not.
Even if the upload is always done, not having the traces showing which artifacts have been uploaded makes it difficult to trace back which build did what.

**To Reproduce**
Here is a very simple scripted pipeline to reproduce the issue:
```
node('mynode') {
    timestamps {
        def artifactoryOutputRepo = 'myrepo'
        stage('Publish') {
            sh 'echo "debug" > file1.bin'
            def server = Artifactory.server 'your-artifactory-server'
            def uploadSpec = """{
                "files": [
                    {
                        "pattern": "*.bin",
                        "target": "${artifactoryOutputRepo}/"
                    }
                ]
            }"""
            def buildInfo = server.upload spec: uploadSpec, failNoOp: true
        }
    }
}
```

**Expected behavior**
A line in the console always showing the file uploaded:
```
[Pipeline] artifactoryUpload
18:58:31  [consumer_0] Deploying artifact: http://myartifactory.org:80/artifactory/myrepo/file1.bin
```

**Actual behavior**
Inconsistent behaviour, sometimes the line is seen, sometimes it is not. 
Here is the console output when we get nothing at all:
```
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Publish)
[Pipeline] sh
19:18:10  + echo debug
[Pipeline] getArtifactoryServer
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Versions**
- Jenkins Artifactory plugin version: 3.8.1
- Jenkins operating system: Jenkins 2.254 on CentOS Linux release 7.4.1708 (Core)
- Artifactory Version: 6.13.3

**Additional context**
It seems related to the size of the files we upload...maybe the upload is too fast and the logger is destroyed before we get a chance to print?

**Comment by yahavi** [comment]
@dlinares-linux,
Thanks for reporting this issue!
We are working on a fix: https://github.com/jfrog/jenkins-artifactory-plugin/pull/385
We'll keep you updated.

**Comment by yahavi** [comment]
@dlinares-linux
Jenkins Artifactoru plugin 3.10.1 is released. This version includes the fix for this issue. Feel free to upgrade.
We'd appreciate your feedback on that.
