### ISSUE TITLE
rtPublishBuildInfo is broken in 3.6.x, 3.7.x, 3.8.x, 3.9.x, 3.10.0

### ISSUE THREAD

**Issue by freevatar** [jfrog/jenkins-artifactory-plugin#366]
**Describe the bug**
`rtPublishBuildInfo` stopped working starting from `3.6.0` 

**To Reproduce**
```
pipeline {
    agent {
        node {
            label 'master'
        }
    }
    stages {
        stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: 'ARTIFACTORY_SERVER',
                    url: 'https://***.artifactory.***.com/artifactory',
                    credentialsId: '***'
                )
            }
        }
        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: 'ARTIFACTORY_SERVER'
                )
            }
        }
    }
}
```

**Versions**
- Jenkins operating system: `Ubuntu 18.04.5 LTS`
- Jenkins version: `2.249.3 LTS`
- Jenkins Artifactory plugin versions affected: `3.6.x`, `3.7.x`, `3.8.x`, `3.9.0`, `3.10.0`
- Artifactory Version: `6.16.0`

**Additional context**
* `rtPublishBuildInfo` works as a charm on `3.5.0`
* in addition to mentioned error we got issue described here: https://github.com/jfrog/jenkins-artifactory-plugin/issues/265
* `https://***.artifactory.***.com/artifactory` has certificate signed by trusted CA (non self-signed) unlike https://github.com/jfrog/jenkins-artifactory-plugin/issues/265
* `rtDockerPush` and `rtDockerPull` work as a charm on `any version`

**Error Log (from the Pipeline)**
```
java.io.IOException: Could not publish build-info: Error occurred while requesting version information: null
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.sendBuildInfo(ArtifactoryBuildInfoClient.java:268)
<CUT>
```
**Error Log (from the logger: org.jfrog)**
```
Sending build info: Build{<CUT>}

Nov 19, 2020 6:51:17 PM SEVERE org.jfrog.hudson.util.JenkinsBuildInfoLog error

Could not build the build-info object.
org.apache.http.HttpException: No credentials for preemptive authentication
	at org.jfrog.build.client.PreemptiveHttpClient$PreemptiveAuth.process(PreemptiveHttpClient.java:136)
	<CUT>
Caused: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	<CUT>
Caused: org.jfrog.build.util.VersionException: Error occurred while requesting version information: null
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.verifyCompatibleArtifactoryVersion(ArtifactoryBuildInfoClient.java:388)
        <CUT>
```

**Comment by grzn** [comment]
This happens on the latest Jenkins and Artifactory plug-in, when Jenkins is configured with a Proxy.
Without a proxy, or when bypassing the proxy in the plugin configuration, the problem goes away.

**Comment by freevatar** [comment]
Just to clarify what @grzn wrote.

When the proxy is set, `rtPublishBuildInfo` crashes before even trying to establish connection with very confusing log output (see the very first message). That behavior was confirmed by capturing network traffic dump.

As a temporary workaround we provided `bypassProxy: 'true'` option. But it's not clear what to do when proxy is required and there is now way to bypass it.

**Comment by grzn** [comment]
One can easily reproduce this when by running http proxy with ssh locally on the Jenkins host by running ssh localhost -D 8000 and telling Jenkins to use http://localhost:8000 as the proxy.

**Comment by grzn** [comment]
Also, looks related to https://www.jfrog.com/jira/browse/BAP-204.

**Comment by RobiNino** [comment]
Hi @freevatar @grzn ,
Thanks for reporting this issue.
A fix has been merged and will be included in the plugin's upcoming release.

Here's a snapshot version of the plugin that includes the fix:
[https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20201220.132410-5.hpi](https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20201220.132410-5.hpi).

We'd appreciate your feedback on that.

**Comment by RobiNino** [comment]
Hi @freevatar @grzn ,
Jenkins Artifactory plugin 3.10.1 is released. This release includes a fix for this issue. Feel free to upgrade.
We'd appreciate your feedback on that.
