### ISSUE TITLE
Configure GUI completly broke

### ISSUE THREAD

**Issue by Likqez** [jfrog/jenkins-artifactory-plugin#369]
**Describe the bug**
The whole configure page, of a element is broken. It's not only ugly, it also cannot be saved anymore.
As you save, you'll get an empty error box like this: https://i.imgur.com/5G3Lu4R.png
Here you can see the normal page in some screenshots: [img1](https://i.imgur.com/aLntw3n.png), [img2](https://i.imgur.com/sONmOSi.png)

**To Reproduce**
- Update Jenkins from 2.264 to 2.267
- Update Plugin from 3.8.9 to 3.9.0

**Expected behavior**
Nothing. To just work like a charm

**Versions**
- Jenkins Artifactory plugin version: 3.9.0
- Jenkins operating system: official docker image
- Artifactory Version: OSS 7.4.3

**Additional**
I have a CCS Theme installed, the error did persist without the style too.

**Comment by eyalbe4** [comment]
Thank you for reporting this issue @Likqez.
We're aware of it and attempting to resolve it ASAP. We'll soon update this issue.

**Comment by RobiNino** [comment]
Thanks @Likqez for reporting this issue.
We just released version 3.9.1 of the plugin which includes a fix.
We'd appreciate your feedback for it.

**Comment by broomyocymru** [comment]
Hi, I can confirm 3.9.1 has resolved the issue in my environment.
