### ISSUE TITLE
Can't save Artifactory upload/download server setting in Generic-Artifactory Integration

### ISSUE THREAD

**Issue by maksonlee** [jfrog/jenkins-artifactory-plugin#379]
**Describe the bug**
Can't save Artifactory upload/download server setting in Generic-Artifactory Integration

**To Reproduce**
Select Artifactory upload/download server setting in Generic-Artifactory Integration, then save.

**Expected behavior**
Setting can be saved

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.9.1, 3.10.0
- Jenkins operating system: Ubuntu 20.04
- Artifactory Version:

**Additional context**

**Comment by yahavi** [comment]
Thanks for reporting this issue, @maksonlee.
We tried to reproduce in on Jenkins 2.263.1 (Latest) and 2.269 (LTS). Unfortunately it didn't reproduce.  
Can you please specify your Jenkins server version?

**Comment by maksonlee** [comment]
Our Jenkins version is 2.269, and there is no issues if i rollback plugin version to 3.9.0.

**Comment by yahavi** [comment]
@maksonlee,
Can you please provide us with some more information?
1. If you can, a screenshot may help.
2. Do you see any errors/stacktraces in the browser console log? If you are not familiar with it, here is a guide for how to examine the [Firefox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console#Opening_the_Browser_Console) and [Chrome](https://developers.google.com/web/tools/chrome-devtools/open#console) console logs.
3. Do you see any errors/stacktraces in the Jenkins logs? If you're not familiar with the Jenkins logs, here is a [guide](https://www.jenkins.io/doc/book/system-administration/viewing-logs/).

Thanks in advance.

**Comment by maksonlee** [comment]
here is the console log related to artifactory,

configure:1 [DOM] Found 5 elements with non-unique id #artifactoryUrlDeployhttp://artifactory-test:8081/artifactory: (More info: https://goo.gl/9p2vKq) <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​
configure:1 [DOM] Found 5 elements with non-unique id #artifactoryUrlDeployhttp://artifactory:8081/artifactory: (More info: https://goo.gl/9p2vKq) <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlDeployhttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​
configure:1 [DOM] Found 3 elements with non-unique id #artifactoryUrlResolvehttp://artifactory-test:8081/artifactory: (More info: https://goo.gl/9p2vKq) <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory-test:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory-test:​8081/​artifactory">​
configure:1 [DOM] Found 3 elements with non-unique id #artifactoryUrlResolvehttp://artifactory:8081/artifactory: (More info: https://goo.gl/9p2vKq) <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​ <input name=​"artifactoryUrl" id=​"artifactoryUrlResolvehttp:​/​/​artifactory:​8081/​artifactory" type=​"hidden" value=​"http:​/​/​artifactory:​8081/​artifactory">​

**Comment by maksonlee** [comment]
and there is no errors related to artifactory in jenkins.log.

**Comment by yahavi** [comment]
@maksonlee, 
We recently releaesd Jenkins Artifactory plugin 3.10.1. This version includes massive bug fixes. I think https://github.com/jfrog/jenkins-artifactory-plugin/pull/390 may resolve your issue.
Can you please let us know if you still having this issue in 3.10.1?
Thanks!
