### ISSUE TITLE
Plug-in v3.10.1 - Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat.

### ISSUE THREAD

**Issue by DwaineGarden** [jfrog/jenkins-artifactory-plugin#403]
**Describe the bug**
Getting millions of these messages while starting up Jenkins with the new installed Artifactory Plug-in 3.10.1.  Jenkins takes forever to start-up because it's processing these errors.

Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat.

**To Reproduce**
Keep restarting Jenkins with the new 3.10.1 Artifactory Plug-in installed.   Downgrading to previous version stops these messages from showing up.

**Expected behavior**
No error messages while Jenkins is starting up.

**Screenshots**
Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.Arti

**Versions**
- Jenkins Artifactory plugin version:  v3.10.1
- Jenkins operating system: Windows 2008 R2
- Artifactory Version: 6.10.9 rev 61009900

**Additional context**

**Comment by DwaineGarden** [comment]
Running Jenkins 2.263.1

**Comment by yahavi** [comment]
@DwaineGarden,
Thanks for reporting this issue. 
The root cause of this issue is the change introduced by https://github.com/jfrog/jenkins-artifactory-plugin/pull/390.

We are working on a fix and we'll keep you updated.

**Comment by DwaineGarden** [comment]
Thank you...

**Comment by yahavi** [comment]
@DwaineGarden,
Jenkins Artifactory plugin 3.10.2 is released. This release includes a fix for this issue, feel free to upgrade.
We'd appreciate your feedback on that!

**Comment by DwaineGarden** [comment]
Pulling v3.10.3 now....  I'll provide feedback today..

**Comment by DwaineGarden** [comment]
I tested out plug-in v3.10.3.  The error messages did not appear and the plug-in is performing as expected.  
Everything looks good.   Thanks

Dwaine
