### ISSUE TITLE
Jenkins Artifactory Maven Build Log Repeat Output and Chaos

### ISSUE THREAD

**Issue by 15846363412** [jfrog/jenkins-artifactory-plugin#410]
when i use maven3.39 is ok,but maven3.6.x,3.5.4 and so on, Log Repeat Output and Chaos, I can't read it easily 
![image](https://user-images.githubusercontent.com/34851956/103505867-497e3180-4e96-11eb-9a73-8719e79937e4.png)

**Comment by yahavi** [comment]
@15846363412,
Jenkins Kubernetes plugin 1.28.6 is released. 
This release is including this [fix](https://github.com/jenkinsci/kubernetes-plugin/pull/927) that should resolve this issue.
We'd appreciate your feedback on that.

**Comment by 15846363412** [comment]
> @15846363412,
> Jenkins Kubernetes plugin 1.28.6 is released.
> This release is including this [fix](https://github.com/jenkinsci/kubernetes-plugin/pull/927) that should resolve this issue.
> We'd appreciate your feedback on that.

**Comment by 15846363412** [comment]
@yahavi You're welcome

**Comment by yahavi** [comment]
@15846363412,
Is the issue resolved for you in Jenkins Kubernetes plugin 1.28.6?

**Comment by 15846363412** [comment]
@yahavi 
I haven't upgraded this plugin ,the version I'm using is 1.28.0 ,have time to try

**Comment by 15846363412** [comment]
@yahavi 
I just upgraded to version 1.28.6 ,the issue resolved

**Comment by yahavi** [comment]
Thanks, @15846363412!
