### ISSUE TITLE
Failing to deploy a jar to Artifactory using version 13.10.4. Works in 13.10.0

### ISSUE THREAD

**Issue by stevewallone** [jfrog/jenkins-artifactory-plugin#420]
**Describe the bug**
Fails to deploy a jar to artifactory since the recent upgrade to 13.0.4. An exception is thrown.

**To Reproduce**
Executing this block of code fails.

       env.JAVA_HOME = '/usr/local/openjdk-8/jre'
        def server = Artifactory.server "artifactory"
        def buildInfo = Artifactory.newBuildInfo()
        def rtMaven = Artifactory.newMavenBuild()

        rtMaven.tool = '3.3.9'
        rtMaven.deployer releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local', server: server
        rtMaven.run pom: 'pom.xml', goals: 'clean install -Dmaven.test.skip=true', buildInfo: buildInfo

**Expected behavior**
The above code block worked prior to the upgrade.

**Versions**
- Jenkins Artifactory plugin version: 3.10.4
- Jenkins operating system: docker image - jenkins/jenkins:2.263.3-lts-alpine
- Artifactory Version: JFROG Platform - Enterprise Plus 7.11.5

**Additional context**
This appears to be the commit that added the code that's throwing the exception. It looks like it has to do with the version of apache commons. Prior to the commit it was
        String content = IOUtils.toString(in, "UTF-8");
after
        String content = IOUtils.toString(in, StandardCharsets.UTF_8);

https://github.com/jfrog/build-info/commit/93af2755d0756a4f1d59dbbf23336563761eb08b

**Successful execution**
Jenkins Artifactory Plugin version: 3.10.0
14:58:05  Unpacking https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.zip to /usr/share/maven on java8-mvn3-w6gvz
14:58:07  Artifactory integration is enabled
14:58:07  Executing sh script inside container java8-mvn3 of pod java8-mvn3-w6gvz
14:58:07  Executing command: "/usr/local/openjdk-8/jre/bin/java" "-classpath" "/usr/share/maven/boot/*" "-Dmaven.home=/usr/share/maven" "-Dmaven.conf=/usr/share/maven/conf" "-DbuildInfoConfig.propertiesFile=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/buildInfo1268390548977911525.properties" "-Dm3plugin.lib=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/cache/artifactory-plugin/3.10.0" "-Dclassworlds.conf=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/classworlds3374130033987439092conf" "-Dmaven.multiModuleProjectDirectory=/home/jenkins/agent/workspace/_build-test_feature_test-build_2" "org.codehaus.plexus.classworlds.launcher.Launcher" "-f" "pom.xml" "clean" "install" "-Dmaven.test.skip=true" 

**Failed execution**
10:15:19  Jenkins Artifactory Plugin version: 3.10.4
10:15:19  Unpacking https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.1/apache-maven-3.6.1-bin.zip to /usr/share/maven on java8-mvn3-cttwp
10:15:21  Artifactory integration is enabled
10:15:21  Executing sh script inside container java8-mvn3 of pod java8-mvn3-cttwp
10:15:21  Executing command: "/usr/local/openjdk-8/bin/java" "-classpath" "/usr/share/maven/boot/*" "-Dmaven.home=/usr/share/maven" "-Dmaven.conf=/usr/share/maven/conf" "-DbuildInfoConfig.propertiesFile=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/buildInfo5881221937747443536.properties" "-Dm3plugin.lib=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/cache/artifactory-plugin/3.10.4" "-Dclassworlds.conf=/home/jenkins/agent/workspace/_build-test_feature_test-build_2@tmp/artifactory/classworlds7855220019059146424conf" "-Dmaven.multiModuleProjectDirectory=/home/jenkins/agent/workspace/_build-test_feature_test-build_2" "org.codehaus.plexus.classworlds.launcher.Launcher" "-f" "pom.xml" "install" "-Dmaven.test.skip=true" 

**Stack at the bottom of the pipeline -**
10:15:51  java.lang.RuntimeException: Maven build failed
10:15:51  	at org.jfrog.hudson.pipeline.common.Utils.launch(Utils.java:256)
10:15:51  	at org.jfrog.hudson.maven3.Maven3Builder.RunMaven(Maven3Builder.java:115)
10:15:51  	at org.jfrog.hudson.maven3.Maven3Builder.perform(Maven3Builder.java:110)
10:15:51  	at org.jfrog.hudson.pipeline.common.executors.MavenExecutor.execute(MavenExecutor.java:72)
10:15:51  	at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryMavenBuild$Execution.runStep(ArtifactoryMavenBuild.java:62)
10:15:51  	at org.jfrog.hudson.pipeline.scripted.steps.ArtifactoryMavenBuild$Execution.runStep(ArtifactoryMavenBuild.java:48)
10:15:51  	at org.jfrog.hudson.pipeline.ArtifactorySynchronousNonBlockingStepExecution.run(ArtifactorySynchronousNonBlockingStepExecution.java:42)
10:15:51  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
10:15:51  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:15:51  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:15:51  	at java.lang.Thread.run(Thread.java:748)

**Stack within the pipeline**
 [main] ERROR org.jfrog.build.extractor.maven.BuildInfoRecorder - org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
10:15:51  java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:37)
10:15:51  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:88)
10:15:51  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:169)
10:15:51  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
10:15:51  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
10:15:51  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)
10:15:51  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
10:15:51  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
10:15:51  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
10:15:51  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
10:15:51  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
10:15:51  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
10:15:51  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:15:51  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:15:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:15:51  	at java.lang.reflect.Method.invoke(Method.java:498)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
10:15:51  Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
10:15:51  	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:35)
10:15:51  	... 19 more
10:15:51  Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:254)
10:15:51  	at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:243)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:623)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:382)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:370)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$deploy$4(ModuleParallelDeployHelper.java:45)
10:15:51  	at java.lang.Iterable.forEach(Iterable.java:75)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deploy(ModuleParallelDeployHelper.java:43)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$null$1(ModuleParallelDeployHelper.java:33)
10:15:51  	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:15:51  	at java.lang.Thread.run(Thread.java:748)
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String; -> [Help 1]
10:15:51  org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
10:15:51  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
10:15:51  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
10:15:51  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
10:15:51  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
10:15:51  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:15:51  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:15:51  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:15:51  	at java.lang.reflect.Method.invoke(Method.java:498)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
10:15:51  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
10:15:51  Caused by: java.lang.RuntimeException: org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
10:15:51  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:178)
10:15:51  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
10:15:51  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
10:15:51  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)
10:15:51  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
10:15:51  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
10:15:51  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
10:15:51  	... 11 more
10:15:51  Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:37)
10:15:51  	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:88)
10:15:51  	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:169)
10:15:51  	... 17 more
10:15:51  Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
10:15:51  	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deployArtifacts(ModuleParallelDeployHelper.java:35)
10:15:51  	... 19 more
10:15:51  Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
10:15:51  	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:254)
10:15:51  	at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:243)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:623)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:382)
10:15:51  	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:370)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$deploy$4(ModuleParallelDeployHelper.java:45)
10:15:51  	at java.lang.Iterable.forEach(Iterable.java:75)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.deploy(ModuleParallelDeployHelper.java:43)
10:15:51  	at org.jfrog.build.extractor.ModuleParallelDeployHelper.lambda$null$1(ModuleParallelDeployHelper.java:33)
10:15:51  	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:15:51  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:15:51  	at java.lang.Thread.run(Thread.java:748)
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - 
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - To see the full stack trace of the errors, re-run Maven with the -e switch.
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - 
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
10:15:51  [main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by c-koell** [comment]
Also reported in https://www.jfrog.com/jira/browse/HAP-1442

**Comment by yahavi** [comment]
@stevewallone @c-koell 
Thanks for reporting this issue!

Jenkins Artifactory Plugin 3.0.4 is using [IOUtils.toString(InputStream, Charset)](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.nio.charset.Charset-), which presented in Apache IOUtils 2.3, April 2012. For some reason, the Maven resolver chose Apache IOUtils below 2.3, which is very old. This may occur due to another Jenkins plugin that utilizes this version.

I created https://github.com/jfrog/build-info/pull/450 to handle this issue by using [IOUtils.toString(InputStream, String) ](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#toString-java.io.InputStream-java.lang.String-)which is presented in 2.1.

As a workaround, for now, you can use the Jenkins Artifactory plugin 3.10.0.

**Comment by yahavi** [comment]
@stevewallone,

The fix is merged to the master branch and will be included in the next release.

Here is a snapshot which includes the fix:
https://oss.jfrog.org/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-20210131.080303-59.hpi

We'd appreciate your feedback on that.

**Comment by yahavi** [comment]
@stevewallone @c-koell 
Jenkins Artifactory plugin 3.10.5 is released.
This version includes the fix introduced in jfrog/build-info#450. Feel free to upgrade.
We'd appreciate your feedback on that.
