### ISSUE TITLE
Release staging fails on versions 3.10.0 and above

### ISSUE THREAD

**Issue by rgala** [jfrog/jenkins-artifactory-plugin#423]
Release staging fails since 3.10.0. There was a change in GitManager class in way the GIT client is called. Previously it was

`client.checkout(null, branch);`

now it is

`client.checkoutBranch(null, branch);`

The order of parameters is wrong, because **checkoutBranch's** first parameter is branch and second is ref. For **checkout** method the first was ref and the second was branch.

**Comment by rgala** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RobiNino** [comment]
@rgala Thanks again for reporting this issue and creating a PR!
The fix will be included in our next release, here's a snapshot version of the plugin that includes it:
[artifactory-3.10.x-SNAPSHOT.hpi](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.10.x-SNAPSHOT/artifactory-3.10.x-SNAPSHOT.hpi)
