### ISSUE TITLE
Artifactory Jenkins Plugin Steps - Idea behind "rt" prefix?

### ISSUE THREAD

**Issue by dawinter** [jfrog/jenkins-artifactory-plugin#433]
We use Artifactory and Jenkins and try to identify the correct usage of the artifactoy plugin to upload artifacts.
The documentation https://www.jenkins.io/doc/pipeline/steps/artifactory/#artifactoryupload-upload-artifacts here has the steps artifactoryUpload and rtUpload. Both are describing upload artifacts but I could not find the description about the difference or when I should use which. Also the example page https://github.com/jfrog/project-examples/tree/master/jenkins-examples/pipeline-examples does not give a hint

Do you know what "rt" as prefix means? What is the recommened step to use?

**Comment by yahavi** [comment]
@dawinter 
The Jenkins Artifactory plugin's official documentation can be found [here](https://www.jfrog.com/confluence/display/JFROG/Jenkins+Artifactory+Plug-in).
To upload a file using a declarative pipeline use the [rtUpload](https://www.jfrog.com/confluence/display/JFROG/Declarative+Pipeline+Syntax#DeclarativePipelineSyntax-UploadingandDownloadingFiles) step.

The documentation under https://www.jenkins.io/doc/pipeline/steps/artifactory/#artifactoryupload-upload-artifacts is automatically generated by Jenkins for each version, according to the code of the plugin. It exposes all internal and external steps and shows them without any explanation. `artifactoryUpload` is an internal function and therefore should not be used.

Please let us know if you have more questions.
