### ISSUE TITLE
artifactoryPublish task fails when gradle wrapper is used

### ISSUE THREAD

**Issue by SakinaMaster** [jfrog/jenkins-artifactory-plugin#443]
**Describe the bug**
When rtGradle.usesPlugin = false and rtGradle.useWrapper = true, the artifactoryPublish task fails.  
Since rtGradle.usesPlugin = false, the --init-script is ran. But from the screenshots below it can be observed that the init-script doesn't recognize that the wrapper is set to true.

**To Reproduce**
In **Jenkinsfile** set the following params as:  
rtGradle.usesPlugin = false  
rtGradle.useWrapper = true

**In build.gradle:**
Do not utilize Gradle Artifactory Plugin.

**Expected behavior**
Expect to publish artifacts using gradle wrapper and without explicity applying Gradle Artifactory plugin (apply plugin: "com.jfrog.artifactory") in build.gradle

**Screenshots**
<img width="820" alt="Screen Shot 2021-03-23 at 9 56 08 AM" src="https://user-images.githubusercontent.com/41123281/112215902-e8d9d780-8bee-11eb-83c7-18df2c51c364.png">
<img width="825" alt="Screen Shot 2021-03-23 at 10 08 47 AM" src="https://user-images.githubusercontent.com/41123281/112215937-f2633f80-8bee-11eb-85b1-3e80bba400a1.png">

**Versions**
- Jenkins Artifactory plugin version: 3.9.0
- Jenkins operating system: 2.190.31.0.1-fixed
- Artifactory Version: 7.9.0

**Comment by yahavi** [comment]
@SakinaMaster,
Thanks for reporting this.

RealizableTaskCollection.configureEach() [added in Gradle 4.9](https://github.com/gradle/gradle/blob/v4.9.0/subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java#L154).
You are using Gradle 4.3.1 which released almost 4 years ago. This version is no longer supported by the Jenkins Artifactory plugin. The minimal supported Gradle version by the Jenkins Artifactory plugin is 4.10. 

To run the Gradle task, you can start by upgrading your Gradle wrapper version to the latest version under Major 4:
```bash
gradle wrapper --gradle-version 4.10.3 --distribution-type all

```

Read more about the Gradle step under [GradleBuildswithArtifactory](https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax#ScriptedPipelineSyntax-GradleBuildswithArtifactory).

Please let me know if this information helped.

**Comment by SakinaMaster** [comment]
@yahavi,
Thank you for the update.

The information was helpful and it helped me solve my issue.
Thank you.

**Comment by SakinaMaster** [comment]
@yahavi,
This issue still persists after upgrading the Gradle version. I tried testing more projects and I am facing with the same issue. 
Gradle wrapper doesn't seem to work unless the Gradle Artifactory Plugins (apply plugin: "com.jfrog.artifactory" and the dependencies { classpath ("org.jfrog.buildinfo:build-info-extractor-gradle:4.4.18")} ) are explicitly declared in build.gradle. 

<img width="953" alt="Screen Shot 2021-05-12 at 11 32 02 AM" src="https://user-images.githubusercontent.com/41123281/118013214-80b69080-b317-11eb-8429-12a0b8930328.png">
<img width="900" alt="Screen Shot 2021-05-12 at 11 30 55 AM" src="https://user-images.githubusercontent.com/41123281/118013244-87dd9e80-b317-11eb-9e98-e223a317ca2a.png">

**Comment by yahavi** [comment]
@SakinaMaster,
Thanks for your feedback. 
It looks like a different issue. In the Jenkins Artifactory plugin, we use a Gradle init script in order to inject the Gradle Artifactory plugin during the Gradle build and expose the `artifactoryPublish` task.
It looks like the space in `Gradle projects` exposed an issue when finding the Gradle init script.

I've been able to reproduce it on the latest version.
We are working on a fix - https://github.com/jfrog/jenkins-artifactory-plugin/pull/469
As a workaround, you can manually apply the Artifactory Gradle plugin or remove the space from the directory.
We'll keep you updated on it.

**Comment by yahavi** [comment]
@SakinaMaster,
Jenkins Artifactory plugin 3.11.0 is released. This version includes a fix for this issue.
We'd appreciate your feedback on that!
