### ISSUE TITLE
Xray reports 2 high-risk vulnerabilities in the plugin.

### ISSUE THREAD

**Issue by PanC123** [jfrog/jenkins-artifactory-plugin#451]
**Describe the bug**
We back up the Jenkins plugins to the Artifactory every day. And there are 2 high-risk vulnerabilities scanned by xray.

**Expected behavior**
We hope to fix these 2 vulnerabilities. Thanks a lot！

**Screenshots**
![image](https://user-images.githubusercontent.com/12429140/114657749-49a68c80-9d23-11eb-8d7c-37fc167c44e3.png)

**Versions**
- Jenkins Artifactory plugin version: 3.10.6

**Comment by yahavi** [comment]
@PanC123 
Thanks for reporting this issue!
We created #462 to upgrade `commons-codec` and `commons-io` to fixed versions.
The `netty-codec` is a test dependency that came from [mockserver-netty](https://github.com/jfrog/jenkins-artifactory-plugin/blob/artifactory-3.10.6/pom.xml#L486).

Please let us know if there are any other vulnerabilities you see.

**Comment by yahavi** [comment]
@PanC123 
Jenkins Artifactory plugin 3.11.0 is released. This version includes the dependency updates.
Feel free to upgrade. 
We'd appreciate your feedback on that!
