### ISSUE TITLE
Artifactory Trigger stopped working after 3.11.1

### ISSUE THREAD

**Issue by felipecrs** [jfrog/jenkins-artifactory-plugin#487]
**Describe the bug**
After upgrading the plugin to 3.11.1, the Artifactory Trigger functionality stopped working.

**To Reproduce**
I'm not exactly sure, perhaps this can be reproduced by simply upgrading the plugin and testing the functionality.

**Expected behavior**
The build to get triggered.

**Screenshots**
I have no screenshots, but I found the exception in my Jenkins logs:

```log
May 26, 2021 1:46:01 PM SEVERE org.jfrog.hudson.trigger.ArtifactoryTrigger run
Received an error: Cannot construct instance of `org.jfrog.build.client.ItemLastModified` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.apache.http.conn.EofSensorInputStream); line: 2, column: 3]
```

**Versions**
- Jenkins Artifactory plugin version: 3.11.1
- Jenkins operating system: 2.277.4 LTS
- Artifactory Version: 7.16.3

**Additional context**
Downgrading the plugin to 3.10.0 fixed the problem for me.

**Comment by Or-Geva** [comment]
@felipecrs, Jenkins-Artifactory-Plugin 3.11.3 was released and includes the fix for your issue, feel free to upgrade and share your feedback.

**Comment by felipecrs** [comment]
The upgrade fixed my issue. Thank you so much for the prompt reply.
