### ISSUE TITLE
Unable to to select Artifactory Server for artifact resolution in Maven project

### ISSUE THREAD

**Issue by sjmiller** [jfrog/jenkins-artifactory-plugin#493]
**Describe the bug**
`Resolve artifacts from Artifactory` for Maven projects appears to be broken. Server pulldown looks like it has blank entries for each server configured, repo pulldowns are empty, and Refresh Repositories errors without a message.

**To Reproduce**
Create new Maven Project, check the box for `Resolve artifacts from Artifactory`, note that server field contains empty options.

**Expected behavior**
Server should be selectable, should populate `Resolution release repository` and `Resolution snapshot repository` pulldowns, clicking `Refresh Repositories` should work, etc.

**Screenshots**
Artifactory configured:
![Screen Shot 2021-05-28 at 1 56 20 PM](https://user-images.githubusercontent.com/1865962/120030325-ec0d8d00-bfbc-11eb-9848-9b1a8482e5da.png)

New Maven project:
![Screen Shot 2021-05-28 at 2 00 05 PM](https://user-images.githubusercontent.com/1865962/120030413-0e070f80-bfbd-11eb-9a32-cf5501c0a2ba.png)

**Versions**
- Jenkins Artifactory plugin version: 3.11.2
- Jenkins operating system: Ubuntu 18.04
- Jenkins version: 2.277.4
- Artifactory Version: 7.17.11 (SaaS)

**Comment by Or-Geva** [comment]
Thank you @sjmiller  for reporting this issue!
Version 3.11.3 of the Artifactory Plugin includes a fix for this issue.
Looking forward to your feedback for the fix.

**Comment by sjmiller** [comment]
Thank you so much for the quick turnaround, this resolves the issue.
