### ISSUE TITLE
Is there a way to get the url address which caused the jenkins job execution - during its execution?

### ISSUE THREAD

**Issue by moshavnik** [jfrog/jenkins-artifactory-plugin#496]
I configured a jenkins job which to trigger whenever a docker image is pushed to a docker repo on the artifactory.
the jenkins is triggered successfully when an image is pushed.
I can see the url address of the docker in the console output of the jenkins job.

my question is:
is there a way to get that url address during the job execution?
is there any environment variable holding that info so I access it during the execution of the job?

for example - using jira, there is also a capability to trigger a job whenever an issue is updated, and the job being triggered holds an environment variable with the jira issue key so the user can use in the job itself (name of environment variable is JIRA_ISSUE_KEY).

is there something equivalent in your plugin? (something like: "ARTIFACTORY_OBJECT_ID" or something of that sort...)

attached are the job configuration and the console output of the job.
jenkins version: 2.277.4
artifactory plugin version: 3.11.4

![jenkins pipeline console output from artifactory trigger](https://user-images.githubusercontent.com/4751571/120501682-7b0a1300-c3ca-11eb-8c88-1e634f28ec5a.jpg)
![jenkins pipeline job trigger config](https://user-images.githubusercontent.com/4751571/120501687-7ba2a980-c3ca-11eb-8eff-a210722531fc.jpg)

**Comment by yahavi** [comment]
@moshavnik,
Sorry for the late response.

You can get the trigger URL. Here's how to do it:
Scripted pipeline: [instructions](https://www.jfrog.com/confluence/display/JFROG/Scripted+Pipeline+Syntax#ScriptedPipelineSyntax-BuildTriggers) and an [example](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/build-trigger-example/Jenkinsfile#L4).
Declarative pipeline: [instructions](https://www.jfrog.com/confluence/display/JFROG/declarative+Pipeline+Syntax#DeclarativePipelineSyntax-BuildTriggers) and an [example](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/build-trigger-example/Jenkinsfile#L7).

Please let me know if that helped.
