### ISSUE TITLE
IN version 3.11.1 we get an error: Unrecognized field "slf"

### ISSUE THREAD

**Issue by gersonl70** [jfrog/jenkins-artifactory-plugin#499]
**Describe the bug**
Unexpected field exception

**To Reproduce**
As we rolled back to 3.11.0 , appl the 3.11.1 version of the plugin

**Expected behavior**
Handle the field or ignore it 

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.11.1
- Jenkins operating system: war version 2.277.4 running on windows 2016 
- Artifactory Version: 7.19.4

**Additional context**
[consumer_0] An exception occurred during execution:
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "slf" (class org.jfrog.build.client.ArtifactoryUploadResponse), not marked as ignorable (12 known properties: "checksums", "size", "repo", "downloadUri", "path", "statusLine", "created", "errors", "uri", "mimeType", "createdBy", "originalChecksums"])
at [Source: (org.apache.http.conn.EofSensorInputStream); line: 2, column: 12] (through reference chain: org.jfrog.build.client.ArtifactoryUploadResponse["slf"])
at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
at java.lang.Thread.run(Unknown Source).

**Comment by eyalbe4** [comment]
@gersonl70,
Thanks for reporting this issue. 
I believe that the latest Artifactory Plugin release resolves the issue. 
Please let us know if the upgrade resolves this issue for you.

**Comment by gersonl70** [comment]
@eyalbe4
Thank you for the reply.
I have upgraded to the new plugin and this does not have this issue anymore.
