### ISSUE TITLE
Latest Jenkins changes seem to cause issues in some springboot projects

### ISSUE THREAD

**Issue by spellman235** [jfrog/jenkins-artifactory-plugin#500]
**Describe the bug**
After upgrading to Jenkins 2.277, various classnotfound exceptions failing builds happen which seems to be due to https://issues.jenkins.io/browse/JENKINS-65112, so we upgraded the Artifactory Plugin from 3.4.0 to 3.9. After doing so, builds often fail with an "Artifact ___.jar wasn't produced by this build". It seems to be due to the org.springboot.boot plugin being handled differently in this new Jenkins version due to the following change https://support.cloudbees.com/hc/en-us/articles/360057486272--CloudBees-CI-2-277-1-2-Replace-Acegi-Security-with-Spring-Security-upgrade-Spring-Framework, which causes builds with this plugin to fail.

**To Reproduce**
Created a simple project from the jfrog gradle-examples and added a few springboot elements, when commented out this build succeeds and when added the build fails. On older jenkins the build succeeds even with the springboot elements.

**Expected behavior**
Builds should still work as they were working before.

**Versions**
- Jenkins Artifactory plugin version: 3.9+ (tested with latest 3.11.1)
- Jenkins operating system: 2.277.4
- Artifactory Version: 7.17

**Additional context**
 More information has been sent privately.

**Comment by spellman235** [comment]
Using https://github.com/spellman235/jenkex.git
specifically changed the gradle-examples/gradle-example-ci-server/* build.gradles to test this.
sent jenkinsfile and jenkins server directly.

**Comment by yahavi** [comment]
Thanks for reporting this issue.
This issue does not relate to the Jenkins Artifactory plugin. This error will also occur if you publish to non-Artifactory repositories - try to run “gradle publishToMavenLocal”.
Actually, the error came from Gradle: 
> This is caused by the fact that the main jar task is disabled by the Spring Boot application, and the component expects it to be present.

To make it work, enable the jar task in your build.gradle:
```groovy
jar {
   enabled = true
}
```

See full instructions on how to fix it in the Gradle [documentation](https://docs.gradle.org/current/userguide/upgrading_version_6.html#publishing_spring_boot_applications).
Please let me know if that helped.
