### ISSUE TITLE
SECURITY ISSUE - using artifactory trigger requires credentials scope to be "Global" rather than "System"

### ISSUE THREAD

**Issue by moshavnik** [jfrog/jenkins-artifactory-plugin#505]
**Describe the bug**
This is more a security issue rather than "bug".
when enabling artifactory trigger in a pipeline job, the user which perform the check on the defined repo is defined in the jenkins server management credentials.
when defining a user credentials there, there is a scope which defines the availability of those credentials throughout the server.
when defining the scope as "system" - the trigger doesn't work.
when defining the scope as "global" - the trigger DOES work, but the credentials are available to all the users working on the jenkins server. - this posses a MAJOR security threat since those credentials should not be used by any job.

**To Reproduce**
1. define an arifactory server through the manage jenkins screen.
2. add credentials to be used by that server.
3. define a new pipeline job anywhere on the jenkins server.
4. add something to the pipeline which requires credentials.
5. you can see in the credentials list, the credentials we defined in step 2.

**Expected behavior**
I would expect a job requiring credentials to inquire the artifactory server will have the possibility to define those credentials on a different level that the entire server (which would remove the need to define the server level credentials completey)

**Screenshots**
if you need screen shots, please let me know which screenshots, and  I will provide them.

**Versions**
- Jenkins Artifactory plugin version: 3.11.4
- Jenkins operating system: centos 6
- Artifactory Version: 6.11.1
- Jenkins version 2.289.1

**Additional context**
I think there should be an additional issue type here - "Security vulnerability"  or something of that sort...
I will be happy to provide more if - needed.

**Comment by yahavi** [comment]
@moshavnik,
Thanks for requesting this feature!
Jenkins Artifactory plugin 3.16.0 is released. This version includes this feature. Feel free to upgrade.
We'd appreciate your feedback on that!
