### ISSUE TITLE
Artifacts aren't recognized correctly with Spring Boot 2.5+

### ISSUE THREAD

**Issue by Kabennsky** [jfrog/jenkins-artifactory-plugin#508]
**Describe the bug**
Since Spring Boot 2.5+ the gradle build produces a plain jar from the jar task, the fat jar from the bootJar still exists. But the artifactory plugin only recognizes the plain jar now. Even if i skip the jar task as mentioned here:
https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives
The fat jar is still not recognized to publish by the plugin, even stranger it still try to publish a plain jar.
> What went wrong:
> Execution failed for task ':submodule:extractModuleInfo'.
> File '/home/jenkins/workspace/workspace/test/submodule/build/libs/submodule-0.0.1-plain.jar' does not exists, and need to be published!´

In the workspace is only a submodule-0.0.1.jar which was created by the bootJar task, but this seems to be ignored by the plugin. artifactDeploymentPatterns.addInclude("*.jar") doesn't help either.

**To Reproduce**
Create a kotlin gradle project using spring boot web 2.5+ and try to publish the fat jar

**Expected behavior**
The fat jar should be recognized as well as the plain jar. And when a task is skipped and e.g. the plain jar so is not created than the plugin shouldn't try to publish it.

**Versions**
- Jenkins Artifactory plugin version: 3.11.4
- Jenkins operating system: 2.277.2
- Artifactory Version: 6.10.3

**Additional context**
Problem original occured in a multi module project. Tested it with a new Project without sub modules, same problem occures. So i would say thats not a multi-module problem.

**Comment by yahavi** [comment]
Thanks for reporting this issue.
This issue does not relate to the Jenkins Artifactory plugin. This error will also occur if you publish to non-Artifactory repositories - try to run “gradle publishToMavenLocal”.
Actually, the error came from Gradle:
> This is caused by the fact that the main jar task is disabled by the Spring Boot application, and the component expects it to be present.

To make it work, enable the `jar` task add the `bootJar` with a different classifier in your build.gradle:
```groovy
jar {
   enabled = true
}

bootJar {
   classifier = 'application'
}
```

See full instructions on how to fix it in the Gradle [documentation](https://docs.gradle.org/current/userguide/upgrading_version_6.html#publishing_spring_boot_applications).
Please let me know if that helped.

Duplicates #500

**Comment by Kabennsky** [comment]
@yahavi Thanks for your answer but we already tried out all those fixes. Before spring 2.5 everything worked fine. 
The jar task is since spring 2.5 enabled by default that change seems to create the problem.

With gradle publishToMavenLocal i get my fat jar in my local m2 folder:
![image](https://user-images.githubusercontent.com/32191592/122034485-de843f80-cdd1-11eb-957f-238814d52403.png)
But it is not published to my artifactory see moudleInfo.json:
![image](https://user-images.githubusercontent.com/32191592/122034817-2dca7000-cdd2-11eb-9d40-1679b64f2d8c.png)

Here my build.gradle.kts i added the maven-publish plugin so i can try out the publishToMavenLocal:
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("maven-publish")
    id("org.springframework.boot") version "2.5.1"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.5.10"
    kotlin("plugin.spring") version "1.5.10"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.getByName<Jar>("jar") {
    enabled = false
}

publishing {
    publications {
        create<MavenPublication>("bootJava") {
            artifact(tasks.getByName("bootJar"))
        }
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.register("getVersion") {
    println(project.version)
}
```

I have task jar enabled false to prevent gradle creating a plain jar as mentioned in the issue description.

If i enable the jar task by not setting it to false or setting is explicit to true, gradle creates a plain jar additional. Now the plain jar will be pushed to artifactory, but still not my fat jar.

If i set the classifier in the bootJar (btw its deprecated archiveClassifier.set("application") is the new way to go) it only will rename my fat jar und still not be published in artifactory. With gradle publishToMavenLocal i now have the fat jar with the classifier in its name in my local m2 folder.


### Solution
Finally i got it work adding the maven-publish plugin and configure a MavenPublication:
```
publishing {
    publications {
        create<MavenPublication>("bootJava") {
            artifact(tasks.getByName("bootJar"))
        }
    }
}
```
And manually removeing the plain jar and adding the bootJar artifacts:
```
configurations {
    listOf(apiElements, runtimeElements).forEach {
        val jar by tasks
        it.get().outgoing.artifacts.removeIf { it.buildDependencies.getDependencies(null).contains(jar) }
        it.get().outgoing.artifact(tasks.bootJar)
    }
}
```

This will work but i don't like that i have to do that manually now, maybe thats something spring boot is doing wrong now or the artifactory plugin interprets it wrong idk. And i have to use the maven-publish plugin now wich wasn't necessary before.

So if your dont think the behavier of the plugin can be improved so we dont have to do this all extra work the issue can be closed. But still gradle publishToMavenLocal is able do publish it and the artifactory plugin only with manually adding the bootJar artifacts.

**Comment by yahavi** [comment]
@Kabennsky, thanks for the information!
We created https://github.com/jfrog/build-info/pull/531 to prevent publishing JARs when the jar task is disabled.
The fix will be available in the next version.
We'll keep you updated.

**Comment by yahavi** [comment]
@Kabennsky 
Jenkins Artifactory plugin 3.12.5 is released.
This version includes a fix for this issue.
We'd appreciate your feedback on that.
