### ISSUE TITLE
Upgrade to 3.11.4 from 3.11.0 and Generic Artifactory Plugin does not display defined instances anymore

### ISSUE THREAD

**Issue by charbl** [jfrog/jenkins-artifactory-plugin#509]
**Describe the bug**
After the update/upgrade the plugin, any project that was configured to use the generic Artifactory fails to upload artifact to defined Artifactory instance.  Upon review we noticed that the config section for the Generic Artifactory was not correct anymore.  Instead of having the selected defined instance .... the dropdown was blank and did not display any instances .... could not fix or select instance.  When the Jenkins job was run before the issue was found, it tried to use the old defined URL to try and upload the artifact, all looked correct in log - the URL and the artifact but the job still failed ... could not find location was returned.

If we drop back to 3.11.0 .... all is good again.

**To Reproduce**
Steps to reproduce the behavior
Create or have Jenkins job that 
![image](https://user-images.githubusercontent.com/22121000/121732028-50e5de80-cab7-11eb-9d7d-59fdb25c8cd5.png)
Update the plugin to use a defined instance of Artifactory  
Select Server and Repo and the Artifact to upload
![image](https://user-images.githubusercontent.com/22121000/121732232-9acec480-cab7-11eb-8113-13b048555907.png)

Upgrade to 3.11.4
Edit project config and see if the list is empty

**Expected behavior**
Would expect the list for Artifacoty Server, Repo to still display what was configured in past

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.11.4
- Jenkins operating system: Windows running Jenkins 2.289.1
- Artifactory Version: Artifactory Version 6.10.1

**Additional context**

**Comment by yahavi** [comment]
@charbl,
Jenkins Artifactory plugin 3.12.1 is released. This version includes a fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
