### ISSUE TITLE
 Xray Scan generates an exception

### ISSUE THREAD

**Issue by glevy** [jfrog/jenkins-artifactory-plugin#560]
**Describe the bug**
After upgrading to version **3.13.1** an exception is generated when scanning a Docker build
java.lang.IllegalArgumentException: Illegal issue type 'security'. Expecting either 'Security' or 'License'

**Reverting back to 3.12.1 resolves this issue.**

**To Reproduce**
Steps to reproduce the behavior

1. run a Docker build, push it using the plugin and publish the build info.
2. run xrayScan 

**Expected behavior**
execute with no exception, or generate an exception indicating that violations were found.

**Versions**
- Jenkins Artifactory plugin version: 3.13.1
- Jenkins operating system: Docker
- Artifactory Version: 7.19.4

**Comment by Doctorbal** [comment]
Why is this closed? The issue appears to be still outstanding in 3.13.1. Simply reverting back isn't a solution when upgrading to newer version.

**Comment by yahavi** [comment]
@glevy & @Doctorbal 
Jenkins Artifactory plugin 3.13.2 is released and includes a fix for this issue.
We'd appreciate your feedback on that.

**Comment by Doctorbal** [comment]
@yahavi , yes I can verify this works now. Thank you.

**Comment by glevy** [comment]
@yahavi, It is working now.
Thanks!
