### ISSUE TITLE
Gradle 8 depreciates the build file location

### ISSUE THREAD

**Issue by derekscp** [jfrog/jenkins-artifactory-plugin#583]
**Describe the bug**
The Artifactory Gradle Jenkins plugin utilizes setting a buildFile which will be depreciated in Gradle 8.

**To Reproduce**

Create a Jenkins build following the [Jfrog project examples](https://github.com/jfrog/project-examples/tree/2870e610efe333dfd599976efe2f2c3a070001af/gradle-examples) for gradle.

Comment out the "maven {" block and "subprojects {" block in 'project-examples/gradle-examples/gradle-example/build.gradle'. Delete the 'gradle-examples/gradle-example/services/webservice/src/test/java/org/gradle/webservice/TestTestTest.java' file.

Change userWrapper to false and tasks to build with the --warning-mode all flag in the Jenkinsfile. (Used [this](https://github.com/jfrog/project-examples/blob/2870e610efe333dfd599976efe2f2c3a070001af/jenkins-examples/pipeline-examples/declarative-examples/gradle-example/Jenkinsfile) as reference.)

```
useWrapper: false, 
...
tasks: 'build --warning-mode all',
```

Running this build will show the deprecation warning in the Jenkins logs

```
Unpacking https://services.gradle.org/distributions/gradle-7.3-bin.zip to /var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/Gradle_7 on Jenkins
[gradle-plugin-test] $ /var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/Gradle_7/bin/gradle build --warning-mode all -b gradle-examples/gradle-example/build.gradle

Welcome to Gradle 7.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Specifying custom build file location has been deprecated. This is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.3/userguide/upgrading_version_7.html#configuring_custom_build_layout
```

**Expected behavior**
In order to prepare for this behavior, the Gradle plugin will need to take into account that this configuration is deprecated and make the according adjustments.

**Versions**
- Jenkins Artifactory plugin version: 3.13.1

**Comment by yahavi** [comment]
Thanks for reporting this issue, @derekscp!
We created https://github.com/jfrog/jenkins-artifactory-plugin/pull/631 to fix it by making sure that when the `buildFile` parameter is not provided, the -b flag will not be provided to Gradle. 
Feel free to review it, if you want.

We'll let you know once this PR is merged and the plugin is released.

**Comment by yahavi** [comment]
@derekscp,
Jenkins Artifactory plugin 3.16.0 is released. This version includes a fix for this issue - feel free to upgrade.
We'd appreciate your feedback on that!
