### ISSUE TITLE
Include virtual repository keys in repositoryKeys list

### ISSUE THREAD

**Issue by matthewbednarski** [jfrog/jenkins-artifactory-plugin#584]
In order to support staging local repositories behind virtual repositories it would be great if we could have the list of virtual repositories as possible source and target repositories.

At the moment only the local repositories are taken into consideration:

https://github.com/jfrog/jenkins-artifactory-plugin/blob/310974b2b1b2fcbc2c6f00571950bf32dc49af00/src/main/java/org/jfrog/hudson/release/promotion/UnifiedPromoteBuildAction.java#L247-L250

Would it be possible to have the following changes?

```java
        List<String> repos = artifactoryServer.
                getReleaseRepositoryKeysFirst((DeployerOverrider) configurator, build.getParent());

        List<String> virtualRepos = artifactoryServer.getVirtualRepositoryKeys((ResolverOverrider) configurator, build.getParent())
            .stream()
            .map(virtual -> virtual.getValue())
            .sorted()
            .collect(Collectors.toList());

        repos.addAll(virtualRepos);
        repos.add(0, "");  // option not to move
        return repos;
```

**Comment by yahavi** [comment]
@matthewbednarski,
Thank you for using the Jenkins Artifactory plugin.
Jenkins Artifactory plugin 3.18.0 is released. In this release, we added support for virtual repositories in the interactive promotion.

The release should be available in the Jenkins plugin registry in a few hours.
We'd appreciate your feedback on that.
