### ISSUE TITLE
NoClassDefFoundError BooleanUtils

### ISSUE THREAD

**Issue by ElfoLiNk** [jfrog/jenkins-artifactory-plugin#597]
**Describe the bug**
NoClassDefFoundError when trying to push a docker image to artifactory with rtDocker.push

```
docker exec .... java -Djava.io.tmpdir=/home/jenkins/workspace/XXX@tmp/artifactory/javatmpdir -cp /home/jenkins/workspace/XXX@tmp/artifactory/cache/artifactory-plugin/3.14.2/* org.jfrog.build.extractor.docker.extractor.DockerPush
Dec 13, 2021 6:36:06 PM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
INFO: Pushing image: XXX
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/BooleanUtils
	at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:442)
	at org.jfrog.build.extractor.docker.DockerJavaWrapper.getDockerClient(DockerJavaWrapper.java:76)
  	at org.jfrog.build.extractor.docker.DockerJavaWrapper.pushImage(DockerJavaWrapper.java:41)
  	at org.jfrog.build.extractor.docker.extractor.DockerPush.execute(DockerPush.java:84)
  	at org.jfrog.build.extractor.packageManager.PackageManagerExtractor.executeAndSaveBuildInfo(PackageManagerExtractor.java:34)
  	at org.jfrog.build.extractor.docker.extractor.DockerPush.main(DockerPush.java:69)
  Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.BooleanUtils
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  	... 6 more
```

**To Reproduce**
Got this error after updating from Jenkins 2.303.2 and Artifactory plugin 3.13.2 to Jenkins 2.319.1 and Artifactory plugin 3.14.2

**Expected behavior**
rtDocker.push should be able to execute

**Screenshots**

**Versions**
- Jenkins Artifactory plugin version: 3.14.2
- Jenkins operating system: 2.319.1
- Artifactory Version: 7.27.6

**Additional context**

**Comment by Or-Geva** [comment]
@ElfoLiNk, thanks for reporting this issue, I have opened a fix [PR](https://github.com/jfrog/build-info/pull/584) and I will update this thread once it is released.

**Comment by ElfoLiNk** [comment]
Hi @Or-Geva i think we are missing this update https://github.com/docker-java/docker-java/pull/1746 on dockerjava to use lang3 like @ebariaux mentioned in https://github.com/jfrog/build-info/pull/580

**Comment by exoemay** [comment]
We see the same issue here. Is the last working version known, so we can downgrade the plugin?

**Comment by yahavi** [comment]
@ElfoLiNk @exoemay 
Thanks for your feedback.
As you may noticed, using commons-lang 2 caused some issues such as https://github.com/jfrog/jenkins-artifactory-plugin/issues/556. As a result, we decided to update all usages of commons-lang 2 to commons-lang 3.

Unfortunately, until this moment, docker-java still uses commons-lang 2. The latest commit does include the update, but we are still pending on their next release.

As a temporary workaround, you can downgrade to 3.13.2.
We'll keep you updated.

**Comment by ctx-ioannisa** [comment]
We are seeing the same issue with version `3.14.2`. However, from our build history, it looks like version `3.14.1` was working as well, but I may be wrong on that.

I see the PR fixing this issue is merged. Any update on new release of the plugin?

**Comment by thomaslorentsen** [comment]
Had this issue after upgrading to ```3.14.2```. Required a rollback and restart to get this working again. Any plan for a release?

**Comment by yahavi** [comment]
@ctx-ioannisa @thomaslorentsen 
Thanks for your feedback.
The PR in `docker-java` is merged, but `docker-java` should be released by its maintainers in order to use it. This dependency is not managed by JFrog.
We'll let you know once this dependency gets updated and the plugin is released.

**Comment by tapioreijonen** [comment]
We are seeing the same issue with version 3.14.2 and the blogin was working with version 3.13.2.

**Comment by denysvitali** [comment]
Can confirm, downgrading to 3.14.1 fixes the issue (cc/ @ctx-ioannisa)

**Comment by staticdev** [comment]
Any change of having a bugfix here? This is a critical error breaking all pipelines that sends to Artifactory (main purpose of this plugin).

**Comment by eyalbe4** [comment]
@staticdev,
We'd really like to release a fix, but we're dependent on the maintainers of https://github.com/docker-java/docker-java to publish a new release. The code is already merged to docker-java.

**Comment by sbosx** [comment]
Hi @staticdev,

Any luck on this one? Today we had our Jenkins upgraded together with the plugin at version 3.15.1 and broke for us too.

**Comment by sbosx** [comment]
Or maybe if someone can point me to the hpi file of the 3.14.1 that above it is claimed to still work.

**Comment by cyberarkDevopsCandidate** [comment]
@staticdev is there a Bug open in "docker-java" project ?

**Comment by jeniamayzel** [comment]
@staticdev is there a bug open in "docker-java" project ?

**Comment by staticdev** [comment]
No, the PR merged there mentions only this issue here.

**Comment by yahavi** [comment]
@jeniamayzel @staticdev 
I asked the maintainer for an ETA a few minutes ago: https://github.com/docker-java/docker-java/discussions/1793

**Comment by jeniamayzel** [comment]
@yahavi @staticdev could you suggest, meanwhile, to which artifactory plugin version it is best to downgrade to ?

**Comment by staticdev** [comment]
3.13.2.

**Comment by denysvitali** [comment]
3.14.1 is the last known working version

**Comment by Sjnahak** [comment]
@here getting below error  in rtDocker push step
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang/BooleanUtils`

Jenkins version : 2.319.2
artifactory version : 3.15.3

**Comment by eyalbe4** [comment]
Since the docker-java maintainer don't create a new release, although the fix has already been merged to the code, and we really need to get this issue fixed already, @yahavi has been working on https://github.com/jfrog/jenkins-artifactory-plugin/pull/629 which is a temporary workaround, till docker-jave gets released.
Thanks @yahavi!

**Comment by jeniamayzel** [comment]
@yahavi what it the artifactory plugin updated version with the fix ?

**Comment by yahavi** [comment]
@jeniamayzel we are working on a release at this moments. 
We'll keep you updated.

**Comment by yahavi** [comment]
@jeniamayzel 
You can use this snapshot in the meanwhile:
https://releases.jfrog.io/artifactory/oss-snapshot-local/org/jenkins-ci/plugins/artifactory/3.15.x-SNAPSHOT/artifactory-3.15.x-20220206.083517-1.hpi
We'd appreciate your feedback on it.

**Comment by yahavi** [comment]
@sbosx @ElfoLiNk @staticdev @denysvitali @jeniamayzel @Sjnahak,
Jenkins Artifactory plugin 3.15.4 is released!

This version includes the fix for this issue - feel free to upgrade and share your feedback.

**Comment by denysvitali** [comment]
Thanks! I'll do it ASAP :)

**Comment by MattLud** [comment]
Can confirm that moving to 3.15.4 fixed the issue

**Comment by yahavi** [comment]
Thanks for the feedback, @MattLud!
