### ISSUE TITLE
Documentation artifactoryNpmCi and artifactoryNpmInstall.

### ISSUE THREAD

**Issue by jasonnicholson** [jfrog/jenkins-artifactory-plugin#602]
The documentation related Jenkins Artifactory documentation is sparse at best. It's not even clear how to call the artifactoryNpmCi and artifactoryNpmInstall. What arguments are required and an example would be helpful.

![image](https://user-images.githubusercontent.com/1058191/147184674-35b0a1c6-7347-417d-9673-1e21597ae6db.png)

**Comment by yahavi** [comment]
@jasonnicholson,
These pages are created automatically by Jenkins and they are not the plugin's documentation.
As mentioned in the README and in the plugin main page, the official Jenkins Artifactory plugin documentation can be found [here](https://www.jfrog.com/confluence/display/JFROG/Jenkins+Artifactory+Plug-in).

Specifically, `artifactoryNpmCi` and `artifactoryNpmInstall` are internal methods and shouldn't be used. Instead, to run npm in a declarative pipeline please use `rtNpmInstall` or `rtNpmCi` - see [NPM Builds with Artifactory](https://www.jfrog.com/confluence/display/JFROG/Declarative+Pipeline+Syntax#DeclarativePipelineSyntax-NPMBuildswithArtifactory) for more information. Also, an example can be found [here](https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/declarative-examples/npm-example/Jenkinsfile).

Please let us know if you have any further questions.

**Comment by jasonnicholson** [comment]
Thank you for the clarification. I appreciate the response! :)
