### ISSUE TITLE
build-info.json file missing in 3.15.0+

### ISSUE THREAD

**Issue by mitchelladam** [jfrog/jenkins-artifactory-plugin#614]
**Describe the bug**
prior to version 3.15 after a maven build the build info was written to ./target/build-info.json this file no longer is written

**To Reproduce**
run any build with rtMaven, pipeline or declarative.

**Expected behavior**
The build-info.json file should still be available somewhere, or the publish build info step should also be able to write to a file, or write to the console

**Versions**
- Jenkins Artifactory plugin version: 3.15.1
- Jenkins operating system: docker - jenkins/jenkins:2.319.2-jdk11
- Artifactory Version: 7.11.5

**Additional context**
The build info is an important part of our regulatory builds, its contents need to be part of the build log, there needs to be somewhere to retrieve this data during the build pipeline.
seems to be related to: 
https://github.com/jfrog/jenkins-artifactory-plugin/issues/610
https://github.com/jfrog/build-info/pull/559

**Comment by Or-Geva** [comment]
@mitchelladam, thank you for reporting this issue.
We are thinking of a new way to get the build-info.json during the pipeline. In the scripted syntax, a new function will be added for returning the build-info as a string. For the declarative, there will be a new closure, to enable writing the build-info.json to a file.
Our current backlog is full right now, but we will add this to our roadmap for sure. I will keep this thread updated once we get there.

**Comment by mitchelladam** [comment]
we just tested the latest artifactory plugin 3.18.12 and the build-info.json is back.
no idea when it started putting it back in target/ but it's there now
