### ISSUE TITLE
Add Federated repositories under the list of Maven repositories for Maven Freestyle jobs

### ISSUE THREAD

**Issue by pavanvikas** [jfrog/jenkins-artifactory-plugin#643]
**Is your feature request related to a problem? Please describe.**
We cannot view the Federated repositories under the list of Maven repositories when working with Maven Freestyle jobs, Please find below steps for the same:
1. Configured the JFrog Platform instance under the Jenkins -> Configuration System.
2. Create a Freestyle Job at Jenkins server end
3. Under the Build Environment section, enable the Maven3-Artifactory Integration which will populate the Target releases/snapshots repositories. Under these, I see Maven Federated repo's were missing.

**Describe the solution you'd like to see**
I would like to see the Federated repositories as under the Target releases/snapshots repositories list.

**Describe alternatives you've considered**
As another alternative way, we can provide the Maven Federated repository name in the text box by selecting **Different Value**, trigger the build which deploys the artifacts to the Federated repository from the Jenkins job. 

Please find below Job & Jenkins configuration for the same:

![Job-Config](https://user-images.githubusercontent.com/49061570/156216281-ced81eee-54d4-49d7-871e-35ec59ddfd25.jpg)
![Configuration](https://user-images.githubusercontent.com/49061570/156216283-ab3a60ca-cdf7-4370-872f-aa30cb793cd3.jpg)

**Comment by yahavi** [comment]
@pavanvikas,
Thanks for using the Jenkins Artifactory plugin.
Jenkins Artifactory plugin 3.18.0 is released. In this release, we added support for federated repositories in Maven Freestyle jobs.

The release should be available in the Jenkins plugin registry in a few hours.
We'd appreciate your feedback on that.
