### ISSUE TITLE
Artifacts not being deployed since version 3.16.1

### ISSUE THREAD

**Issue by Jacob-Steele** [jfrog/jenkins-artifactory-plugin#654]
**Describe the bug**
It seems like since version 3.16.0/3.16.1 artifacts aren't being sent anymore to artifactory from Jenkins when the `rtMavenDeployer` context is used from a pipeline.

Since this version we're getting the log output:
```
17:17:17  [main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: deploy artifacts set to false, artifacts will not be deployed...
```

The build for artifactory does end with as successful message of:
```
17:17:17  [main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: deploy artifacts set to false, artifacts will not be deployed...
17:17:17  [main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: publish build info set to false, build info will not be published...
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD SUCCESS
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Total time:  8.295 s
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2022-03-24T21:17:17Z
17:17:17  [main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
```

As well, the builds themselves say that artifacts were deployed to our server as per the screenshot below:
![image](https://user-images.githubusercontent.com/13258085/160015421-8fd57cfc-63b2-43ad-9c83-260cf7f8cf58.png)

But upon clicking one of these links we get a `404` error, as the file was never uploaded to our artifactory instance.

I was able to downgrade our Jenkins instances to `3.15.4` and everything seems to be working again.

**To Reproduce**
We're trying to run something like to following configuration which was working on `3.15.4`.
As a heads up, this is running on a Jenkins 2 workers, not the controller itself.
```
    String userId = sh returnStdout: true, script: "id -u"
    String extraDockerArgs = """-v \"$HOME/.m2\":/var/maven/.m2 \
        -e MAVEN_CONFIG=/var/maven/.m2 \
        --user ${userId}"""

    docker.image('maven:3.6.3-openjdk-8').inside("${extraDockerArgs}") {
        rtServer (
            id: 'artifactory-server-id',
            url: 'http://internal-artifactory-server',
            credentialsId: 'artifactory-creds-id'
        )

        rtMavenDeployer (
            id: 'MAVEN_DEPLOYER',
            serverId: 'artifactory-server-id',
            releaseRepo: 'libs-release-local',
            snapshotRepo: 'libs-snapshot-local'
        )

        rtMavenResolver (
            id: 'MAVEN_RESOLVER',
            serverId: 'artifactory-server-id',
            releaseRepo: 'libs-release',
            snapshotRepo: 'libs-snapshot'
        )

        rtMavenRun (
            pom: 'pom.xml',
            goals: 'clean compile jar:jar install:install',
            opts: '-Duser.home=/var/maven -DskipTests',
            deployerId: 'MAVEN_DEPLOYER',
            resolverId: 'MAVEN_RESOLVER'
        )
    }
```

I've also tried adding `deployArtifacts: true` to `rtMavenDeployer` based on the docs at https://www.jenkins.io/doc/pipeline/steps/artifactory/#rtmavendeployer-set-maven-deployer. Even with this property set the artifacts aren't being pushed and we're still getting the log.
```
17:17:17  [main] INFO org.jfrog.build.extractor.maven.BuildDeploymentHelper - Artifactory Build Info Recorder: deploy artifacts set to false, artifacts will not be deployed...
```

**Expected behavior**
Artifacts push to our artifactory server

**Versions**
- Jenkins Artifactory plugin version: `3.16.1`
- Jenkins operating system: Running in docker on Ubuntu 18.04. Jenkins version: `2.332.1`
- Artifactory Version: `3.4.2`

**Additional context**
If you need anymore information feel free to reach out. I haven't had a chance to look at the source code yet for this plugin to try and troubleshoot it myself. I may take a look in the next few days to see what's changed since `3.15.4` depending on if I have time available.

**Comment by eyalbe4** [comment]
Thanks for reaching out @Jacob-Steele.
I believe that adding "deploy" to the list of goals will resolve the issue. The reason why this worked for you with previous versions of the plugin is because of a bug, causing artifacts to be deployed in some cases, even if the "deploy" goal wasn't added. 
BTW, the "install" goal (and not install:install) will also trigger deployment. This is for backward compatibility reasons.

**Comment by Jacob-Steele** [comment]
@eyalbe4 Thank you so much for the information and the help! 
I changed the goals around to being `clean compile jar:jar install` instead and this worked!
We'll probably look into changing this eventually to using `deploy` as well.

Thanks again for responding so fast, really appreciate it.

**Comment by eyalbe4** [comment]
I'm happy this resolved the issue @Jacob-Steele!
