### ISSUE TITLE
rtDockerPush intermittent hang/timeout

### ISSUE THREAD

**Issue by Sickafant** [jfrog/jenkins-artifactory-plugin#663]
**Describe the bug**
Intermittently, the rtDockerPush step will reach a point where it tries to get the manifest file, but sits there forever. It will only timeout due to Jenkinsfile timeout configuration:

```
00:19:45  Executing command: /bin/sh -c git log --pretty=format:%s -1
00:19:47  [dockerpush-test_PR-1] $ java -Djava.io.tmpdir=/home/jenkins/workspace/dockerpush-test_PR-1@tmp/artifactory/javatmpdir -cp /home/jenkins/workspace/dockerpush-test_PR-1@tmp/artifactory/cache/artifactory-plugin/3.16.1/* org.jfrog.build.extractor.docker.extractor.DockerPush
00:19:48  Apr 16, 2022 6:19:48 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:19:48  INFO: Pushing image: docker.artifactory-mydomain.org/testpush:latest
00:19:50  Apr 16, 2022 6:19:50 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:19:50  INFO: Searching manifest for image "docker.artifactory-mydomain.org/testpush:latest" in "https://artifactory-mydomain.org/artifactory" under "docker" repository
00:19:50  Apr 16, 2022 6:19:50 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:19:50  INFO: Searching manifest in path: docker/testpush/latest
00:19:50  Apr 16, 2022 6:19:50 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:19:50  INFO: Trying to download manifest from docker/testpush/latest/manifest.json
Cancelling nested steps due to timeout
[Pipeline] }
00:21:43  ERROR: Couldn't execute docker task. InterruptedException:
Exception: null
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
Finished: ABORTED
```

**To Reproduce**

Jenkinsfile example code with a toy example. The image built is a minimal `scratch` image with a small txt COPY'd in:
```
...
        stage ('Push docker image') {
          steps {
            sh 'docker build . -t docker.artifactory-mydomain.com/testpush:latest'
            rtServer id: 'myserver'
            rtDockerPush serverId: 'myserver',
              image: 'docker.artifactory-mydomain.com/testpush:latest',
              targetRepo: 'docker'
          }
        }
...
```

**Expected behavior**
It should fetch the manifest quickly and finish the push, like so:

```
...
00:49:49  INFO: Trying to download manifest from docker/testpush/latest/manifest.json
00:49:50  Apr 16, 2022 6:49:50 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:49:50  INFO: Fetching details of published docker layers from Artifactory...
00:49:51  Apr 16, 2022 6:49:51 AM org.jfrog.build.extractor.packageManager.PackageManagerLogger info
00:49:51  INFO: Successfully pushed docker image: docker.artifactory-mydomain.com/testpush:latest
```

In cases where it somehow gets stuck, I'd expect there to be some sort of connect timeout as well. If I don't set a Jenkinsfile timeout, the build will stay stuck until I manually abort it.

**Versions**
- Jenkins Artifactory plugin version: 3.16.1
- Jenkins operating system: debian (docker lts jenkins 2.332.2)
- Artifactory Version: 7.33.12

**Additional context**
This is noticed when running on an agent that is a container ECS task in AWS ECS EC2 cluster, building an image with a "docker outside docker" /var/run/docker.sock mount configuration. Using `amazon-ecs:1.41` plugin.

**Comment by Or-Geva** [comment]
Thank you for reporting this issue @Sickafant!.
Your push's configuration may be incorrect for a couple of reasons:
```
00:19:48  INFO: Pushing image: docker.artifactory-mydomain.org/testpush:latest
```
It is possible that the image name does not include the Docker repository?. The correct pattern should look like this:<domain>/<repository>/<image-tag>:<tag>

```
00:19:50  INFO: Trying to download manifest from docker/testpush/latest/manifest.json
```
Are you pushing to the 'docker' repository? If not, set the targetRepo property.

**Comment by Sickafant** [comment]
Thanks for the quick response @Or-Geva ,

Yes, in my case I have setup `docker` virtual repo with a subdomain/nginx proxy of docker.artifactory-mydomain.com to point to the repo. There'd be a default deploy local repo that the push ends up in.

The push succeeds most of the time, but maybe there is some networking issue that occasionally makes the plug-in unresponsive. I ran a packet capture and found that when it hangs, there is no DNS request to resolve the ip of my artifactory domain, and no SYN to initiate a connection. So that's pretty strange, but I'd expect the plug-in to detect this network hiccup and retry. 

Instead the workaround so far is for me to add timeouts and retries in the jenkinsfile, wrapping the rtDockerPush to force it to retry.

**Comment by Or-Geva** [comment]
@Sickafant, thanks for the quick response.
We'll look into this. I will keep this thread updated.

**Comment by Or-Geva** [comment]
@Sickafant, did you try modifying the plugin's timeout ?.
You can find it under Manage Jenkins -> Configure System. 
Scroll down to the JFrog section and click on advance.

**Comment by Sickafant** [comment]
@Or-Geva , yes, I tried out shortening it from the default 300s to 60s, but it showed no difference in behaviour.

**Comment by Or-Geva** [comment]
@Sickafant, I verified that the plugin's HTTP client handles connection timeout properly.
We create the HTTP client [here.](https://github.com/jfrog/build-info/blob/master/build-info-extractor-docker/src/main/java/org/jfrog/build/extractor/docker/types/DockerImage.java#L228) and set up the timeout [here](https://github.com/jfrog/build-info/blob/master/build-info-client/src/main/java/org/jfrog/build/client/PreemptiveHttpClientBuilder.java#L182).
Artifactory Jenkins plugin doesn't seem to cause any problems. It's likely that the problem lies within your infrastructure. I recommend contacting JFrog support so they can investigate it from your side.

**Comment by Sickafant** [comment]
Thanks @Or-Geva, I'll raise a support ticket with them. Closing.
