### ISSUE TITLE
Artifactory BuildInfo pointing to wrong URL

### ISSUE THREAD

**Issue by viswanadhganesh** [jfrog/jenkins-artifactory-plugin#688]
Hello Team

We recently upgraded Artifactory to 7.38.8. After that **jenkins-artifactory-plugin** is not working as expected. 

When we clicked on **"artifactory build info"** as shown in the first screenshot, it is redirecting to empty page as shown in the second screenshot.

![image](https://user-images.githubusercontent.com/109945550/180948819-6d3d3246-2e6c-4b41-b636-f4452e7f81ea.png)
![image](https://user-images.githubusercontent.com/109945550/180948923-b25b0e78-1505-413b-8848-01f2bb743f5b.png)

Earlier when clicks on **"artifactory build info"** it will redirect to a new page where we can browse artifacts.

But now it is redirecting to empty page.

We noticed a change in the URL when clicks on build info. Earlier the URL was  **https://xxxxxxx/ui/native/..** 

But now It is **https:/xxxxx/artifactory/webapp/...**

Requesting your help to fix the issue.

Regards
Viswanadh
MBRDI

**Comment by sebracs** [comment]
Previously Artifactory 7 seems to have forwarded you from the legacy Artifactory 6 url https://myartifactory.example/artifactory/webapp/builds to the correct https://myartifactory.example/ui/builds . Now at least with Artifactory version 7.41.7, this forwarding seems not to happen anymore. Since Artifactory 6 is EOL for a while now anyway, can this plugin be changed to provide the Artifactory 7 compatible URL?

**Comment by imanzhulin** [comment]
@jfrogbot this issue has a major severity, does anyone work on this?

**Comment by Hickstone** [comment]
I've got the same problem, but was able to resolve it. In the JFrog Platform Instances section of the global Jenkins configuration you have to set the JFrog Platform URL for every Artifactory instance. In older versions there was only the field JFrog Artifactory URL that is now in the Advanced Configuration section.
When you only set the JFrog Artifactory URL the url is /webapp/builds
When you set the JFrog Platform URL also (without the artifactory/ part) the url is ui/builds

**Comment by imanzhulin** [comment]
Thanks, it helped. I assume the issue can be closed
