### ISSUE TITLE
Maven Artifact snapshot links do not resolve correctly on repositories which have a "unique" snapshot repository.

### ISSUE THREAD

**Issue by AnandDJFrog** [jfrog/jenkins-artifactory-plugin#689]
**Describe the bug**
When publishing maven artifacts to Artifactory using the plugin, the Jenkins build record will include a list of published maven artifacts. In the case of publishing these artifacts to a snapshot repository where the policy is set to unique, the snapshots will named in Artifactory with the timestamp of the publishing (see below).

![Screen Shot 2022-07-28 at 5 16 56 PM](https://user-images.githubusercontent.com/86686671/181657848-1b7e59fe-114f-481e-9ddf-230be2efb223.png)

The links in the Maven artifacts however do not append this timestamp, resulting in a 404 when a user ends up clicking those links.

**To Reproduce**

1. Set up artifactory and do a quick set up for maven repositories to create maven repos for this reproduction. Make sure the snapshot policy on the snapshot repos is set to "unique".

2. Set up the sample maven deploy project to publish to these instances and these repos, set deployArtifacts to true, and run the build to publish the artifacts and build info to artifactory.

https://github.com/jfrog/project-examples/blob/master/jenkins-examples/pipeline-examples/scripted-examples/maven-deploy-example/Jenkinsfile

3. Navigate to the "Maven Artifacts" section for this build run in Jenkins.

![Screen Shot 2022-07-28 at 5 08 36 PM](https://user-images.githubusercontent.com/86686671/181658221-7769b437-ebdb-4ffd-847f-232f1f4b8758.png)

4. Click one of the artifact links (here the example is multi1-3.7-SNAPSHOT.jar).

![Screen Shot 2022-07-28 at 5 09 36 PM](https://user-images.githubusercontent.com/86686671/181658332-e50b41da-e847-48ed-bb47-220ab316cde5.png)

5. Observe the 404.

![Screen Shot 2022-07-28 at 5 25 18 PM](https://user-images.githubusercontent.com/86686671/181658422-736136b8-8368-4909-8314-158ea9b07b0c.png)

6. Find the actual artifact in Artifactory and note that it has the timestamp added (replacing "SNAPSHOT").

![Screen Shot 2022-07-28 at 5 16 56 PM](https://user-images.githubusercontent.com/86686671/181658490-7bf7da1d-b7d0-4744-b08b-60e283ac4bc3.png)

7. Try entering the URL with the timestamp replacing "SNAPSHOT" appropriately and note that it downloads successfully.

![Screen Shot 2022-07-28 at 5 30 11 PM](https://user-images.githubusercontent.com/86686671/181658921-d97556ed-95ed-44c6-9b40-7e1dd67c2800.png)

**Expected behavior**
When we click the link in Jenkins, we do not want to see the 404 but rather for the artifact to be downloaded as described in step 7 of the reproduction above.

**Versions**
- Jenkins Artifactory plugin version: 3.16.2
- Jenkins operating system: Version 2.332.3 on Mac
- Artifactory Version: 7.41.6

**Comment by AnandDJFrog** [comment]
This issue has been reviewed by our plugin developers who have advised that this is the expected behavior. The links provided are used to access the latest available snapshot. In order to be able to access a snapshot through them, the snapshot should be renamed not to include the timestamp.

**Comment by dahnyou** [comment]
Hello, what do you mean by "In order to be able to access a snapshot through them, the snapshot should be renamed not to include the timestamp."? Where should this be configured?
