### ISSUE TITLE
Build scan - missing issueType Operational_Risk

### ISSUE THREAD

**Issue by glevy** [jfrog/jenkins-artifactory-plugin#706]
**Describe the bug**
An exception is being generated while running xrayScan.
java.lang.IllegalArgumentException: Illegal issue type 'Operational_Risk'. Expecting either 'Security' or 'License'

**To Reproduce**
run xrayScan on a published build

**Versions**
- Jenkins Artifactory plugin version:  3.17.2
- Jenkins operating system: Linux
- Xray Version 3.54.5
- Artifactory Version 7.41.7 

**Additional context**
it doesn't seem to be supported in the current code.

**build-info-client/src/main/java/org/jfrog/build/client/artifactoryXrayResponse/Issue.java**

```
public IssueType getIssueType() {
        switch (StringUtils.defaultString(getType()).toUpperCase()) {
            case "SECURITY":
                return IssueType.SECURITY;
            case "LICENSE":
                return IssueType.LICENSE;
        }
        return null;
    }

```

**Comment by glevy** [comment]
**build-info-extractor/src/main/java/org/jfrog/build/extractor/buildScanTable/BuildScanTableHelper.java**

```
 private void addElement(Issue issue, InfectedFile infectedFile) {
        Issue.IssueType issueType = issue.getIssueType();
        if (issueType == Issue.IssueType.SECURITY) {
            securityViolationsTable.addElement(issue, infectedFile);
        } else if (issueType == Issue.IssueType.LICENSE) {
            licenseViolationsTable.addElement(issue, infectedFile);
        } else {
            **throw new IllegalArgumentException(String.format("Illegal issue type '%s'. Expecting either 'Security' or 'License'", issue.getType()));**
        }
    }
```

**Comment by yahavi** [comment]
@glevy,
Thanks for reporting this issue.
Jenkins Artifactory plugin 3.17.3 includes the [fix](https://github.com/jfrog/build-info/pull/675) for this issue.
Feel free to upgrade- we'd appreciate your feedback on that!
