### ISSUE TITLE
Make ivy dependency optional

### ISSUE THREAD

**Issue by jonesbusy** [jfrog/jenkins-artifactory-plugin#713]
Hi,

What is the reason to have a plugin dependency to ivy ? We need the Artifactory plugin but don't want the ivy jobs to be available for our Jenkins users.

Can we remove this hardcoded dependency and make it optional ?

Best regards,

Valentin

**Comment by yahavi** [comment]
Hi, @jonesbusy,
Thanks for reporting this issue. Per your request, we made this dependency optional.
This change takes place in the latest released Jenkins Artifactory plugin version 3.17.4.
Feel free to upgrade. We'd appreciate your feedback on that.

**Comment by jonesbusy** [comment]
Hi,

Already upgraded and we were able to remove the ivy dependency.

Thanks for the quick action
