### ISSUE TITLE
java.lang.IllegalArgumentException: argument count mismatch between [JENKINS-72499]

### ISSUE THREAD

**Issue by javadan** [jfrog/jenkins-artifactory-plugin#914]
**Describe the bug**

In System config, I can add my Artifactory:

Found JFrog Artifactory 7.71.11 at http://my.ip.address:8082/artifactory
JFrog Distribution not found at http://my.ip.address:8082/distribution

 

But when configuring a job/task and selecting Maven3-Artifactory Integration, when i click 'Refresh Repositories', it hangs, and the error shows in the logs:

 
`
Caught unhandled exception with ID 26517eaf-7f15-4958-b42a-e69d82cba7e5 java.lang.IllegalArgumentException: argument count mismatch between [{},"http://my.ip.address:8082/artifactory","","admin","\{AQAyeK7jdywK0B3O//jV0=}",true] and [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, boolean] at org.kohsuke.stapler.MetaClass$JavaScriptProxyMethodDispatcher.doDispatch(MetaClass.java:655) at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900) at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900) at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:836) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900) at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698) at org.kohsuke.stapler.Stapler.service(Stapler.java:209) at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163) at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76) at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160) at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:154) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94) at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110) at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227) at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87) at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63) at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99) at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111) at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38) at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) at org.eclipse.jetty.server.Server.handle(Server.java:563) at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598) at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277) at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) at java.base/java.lang.Thread.run(Thread.java:1583)
`
 

**To Reproduce**

In System config, Add Artifactory URL:
`Found JFrog Artifactory 7.71.11 at http://my.ip.address:8082/artifactory`

Select Maven3-Artifactory Integration, click 'Refresh Repositories' 

**Expected behavior**
Expect it to refresh repositories

**Versions**
- Jenkins Artifactory plugin version: 4.0.1
- Jenkins operating system: Version 2.426.2
- Artifactory Version: JFrog Artifactory 7.71.11

**Comment by c-koell** [comment]
We see the same Exception

**Comment by swinter13** [comment]
Same exception

- plugin 4.0.3
- jenkins 2.443
- artifactory 7.77.3

From the system log:

> Jenkins is fully up and running
> 
> Feb 06, 2024 11:05:34 AM WARNING hudson.init.impl.InstallUncaughtExceptionHandler handleException
> 
> Caught unhandled exception with ID 8ae913c1-46d2-49da-aa90-94f692a00812
> java.lang.IllegalArgumentException: argument count mismatch between [{},"http***********:8082/artifactory","j*****t","","{A********=}",true] and [class java.lang.String, class java.lang.String, class java.lang.String, class java.lang.String, boolean]
> 	at org.kohsuke.stapler.MetaClass$JavaScriptProxyMethodDispatcher.doDispatch(MetaClass.java:655)
> 	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
> 	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:475)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:770)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
> 	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:836)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:900)
> 	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:698)
> 	at org.kohsuke.stapler.Stapler.service(Stapler.java:209)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
> 	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
> 	at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76)
> 	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
> 	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:154)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
> 	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
> 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:110)
> 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
> 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
> 	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
> 	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
> 	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
> 	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
> 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
> 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
> 	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
> 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
> 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
> 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
> 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
> 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
> 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
> 	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by javadan** [comment]
Any chance we can bump this bug ?  

Presumably it's some straightforward missing parameter issue, related to ArtifactoryMaven3Configurator.java  ?  

Somewhere it's trying to put
Empty List, String, String, String, String, boolean 
into 
String, String, String, String, boolean

So that Empty List is not supposed to be there.

Selecting an Artifactory to build a project with Maven is pretty important for this plugin, no?

**Comment by hfskappel** [comment]
any updates or workarouds here? I get the same error with v4.0.6

**Comment by yahavi** [comment]
@javadan @c-koell @hfskappel

Thank you for reporting this issue. The Jenkins Artifactory plugin version 4.0.7 has been released and includes a [fix](https://github.com/jfrog/jenkins-artifactory-plugin/pull/945) for this problem. Please upgrade and let us know your feedback.

**Comment by swinter13** [comment]
Working for me now in Jenkins 2.466. Thanks!
